### ISSUE TITLE
Spanish Support

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#101]
A decent amount of PVTA's ridership is from the Springfield/Holyoke area, and a significant portion of this population speaks Spanish natively.  As such, I think an app that targets them should include Spanish localization.

Cordova has a plugin called [globalization](https://github.com/apache/cordova-plugin-globalization)(which is also the title of a great Pitbull album) that will help us figure out the desired language.

It seems as though the [Angular Translate extension](https://angular-translate.github.io) can help us with the actual injecting of strings into the UI.

This (and all other _satco_ labeled issues) should not be implemented until after a meeting with the PVTA has determined that this WILL be their official app.

**Comment by sherson** [comment]
PVTA is looking into the best way to implement Spanish support in an "official" PVTA app. 

PVTA thinks the approaches we're considering are probably fine, but they want to double-check that this is not considered a "vital" document (the example they cited was that Google Translate doesn't meet [Title 6](https://www.justice.gov/crt/title-vi-civil-rights-act-1964-42-usc-2000d-et-seq) requirements).

**Comment by akaplo** [comment]
Lack of being a PVTA-backed app essentially voids this issue, as analytics show no language requests other than English.  Should this change, this issue can be reopened.

(Ionic/Angular 2.0 will make translations much easier... another reason to wait/forget about it).
