### ISSUE TITLE
Add CodeClimate Integration to PRs

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#104]
This is something that someone with total access to the UMTS organization must do.

@dfaulken, @werebus, @sherson.

**Comment by werebus** [comment]
All set, I think :question:

I won't close this until one works.

Also, I'm curious. I think this sort of mention would have worked:  @umts/owners (at the expense of bothering Metin and Logan)

**Comment by akaplo** [comment]
Looks good to me! Thanks!
