### ISSUE TITLE
Stop Getting Directions By Default

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#114]
Now that mapping a stop gets you walking directions to it, we should change it from being the default.

When mapping, we should just plot the stop.  Perhaps add a bar/ button to the bottom that, when clicked, would slide the map up and give you walking directions.  This would save a TON of Maps API calls.

**Comment by bgregg** [comment]
I will work on this since I did all of the logic for this controller. But @akaplo, did you want this for Friday? I put it as Beta 4 right now, but I may be able to work it in (but it may require some sleepless nights haha)

**Comment by akaplo** [comment]
Best to wait for beta 4.  I'd rather have something stable for Friday with the PRs we've got.

**Comment by akaplo** [comment]
@bgregg I can take this if you don't want to work on it.
