### ISSUE TITLE
VehicleMapController Never Renders Map

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#116]
The `VehicleMapController` on master has trouble about half the time (in my experience) in mapping buses that have been selected **via the RouteController**.

Console error:

>  Error: null is not an object (evaluating 'new google.maps.LatLng')
> 
> placeVehicle@http://localhost:8100/js/controllers/vehicle-map-controller.js:16:30
> 
> http://localhost:8100/js/controllers/vehicle-map-controller.js:22:17

Steps to reproduce:
1. To to the page for a route
2. Click on a vehicle on that route
3. Attempt to map said route

**Comment by bgregg** [comment]
I'll look into it

**Comment by bgregg** [comment]
So I just tried it with 10 different routes (and every vehicle on said routes), and it worked everytime. Not sure where the issue is coming from. @akaplo, maybe today in 320 you can show me what you mean?

**Comment by akaplo** [comment]
Maybe my computer (and/or internet and/or location services) was/were playing tricks on me. I'll try to reproduce when I see you and we can close this if I fail to do so

**Comment by akaplo** [comment]
Closed because this has been proven false, at least on the first load of the map (however, see #124).
