### ISSUE TITLE
Split services.js into separate files

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#120]
The file is like 400 lines long and as such has a CodeClimate rating of F--- (well, an F, but if it could...).

**Comment by bgregg** [comment]
I actually thought of this when I was doing a tutorial on Angular a few months ago. Shouldnt be too difficult to do. The more abstraction the better!

**Comment by nmonti** [comment]
Since most of these are factories, should it be renamed (for example) `data-factory.js`?

**Comment by akaplo** [comment]
I would say yes.

**Comment by nmonti** [comment]
Should I change them within the branch I made?

**Comment by akaplo** [comment]
Sure!  I just saw your PR; looks good!  I'll take a closer look after class.

**Comment by nmonti** [comment]
Don't be looking at work in class, dammit! :p
