### ISSUE TITLE
Route Map doesn't render in specific edge case

### ISSUE THREAD

**Issue by bgregg** [umts/pvta-multiplatform#124]
If you redirect to a route map from another route map, the second one will not render. However it works if you have redirected there using the app's back button (not the browser back button). Bizarre. See #122.

**Comment by akaplo** [comment]
This also applies to Vehicle maps. #117 also contains this issue.

**Comment by akaplo** [comment]
Still having trouble figuring this out.  I don't understand what Ionic/Angular/Google are doing when the back button is pressed that they aren't doing when we select a different option in the navigation menu.
