### ISSUE TITLE
Change HTML to Anything Else

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#125]
Because tags, good god.

**Comment by nmonti** [comment]
This might be easier to integrate: https://github.com/pugjs/pug. It also looks like HAML.

I could be wrong, but from what I've seen, HAML belongs to Rails folk, Jade/pug belong to full stack JS folk.

**Comment by akaplo** [comment]
You're right!  I've updated the title accordingly.  Pug looks like it could be just what we're looking for.

**Comment by bgregg** [comment]
Closed #125.
