### ISSUE TITLE
Ion Date Picker Goes Out Of View

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#132]
On Plan Trips, when picking a time to depart while on a small screen, the keyboard pops up **over** the field you're typing into.  I'm not sure if this _can_ be fixed, but it should be looked into.

**Comment by petermarathas** [comment]
On iOS, the screen slides up with the keyboard, so this isn't an issue. For Android, I found <a href="http://ionicframework.com/docs/api/page/keyboard/#android-notes">this</a> which says to add <code><activity android:windowSoftInputMode="adjustResize"></code> to the activity tag in your AndroidManifest.xml file. I'm having trouble emulating Android on my computer, so I can't test it myself.

**Comment by akaplo** [comment]
I'll look into that. Thanks!

**Comment by sherson** [comment]
Can't reproduce
