### ISSUE TITLE
Deleting Data in Storage Settings

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#133]
On Android devices (at least my GS5), when trying to use the StorageSettings page to delete saved favorites/lists/etc, none of the ionicPopups ever pop up, and thus the data never can be deleted.

I'm interested in hearing if @bgregg has this issue on his GS5, if @dfaulken has this on his One, and if @petermarathas has this on his 5S.  In my testing, it worked no-problem in the iOS emulator.

**Comment by petermarathas** [comment]
<a href="https://github.com/umts/pvta-multiplatform/blob/master/www/js/app.js#L116">The controller for storage settings</a> is incorrect, because I missed a word when trying to fix the merge conflict :expressionless:

**Comment by petermarathas** [comment]
Fixed now

**Comment by petermarathas** [comment]
Unless it still isn't working on your phone, pull from master and try it again.

**Comment by akaplo** [comment]
It's fixed! It was an issue in my iOS emulator as well (I just discovered this) it works fine now.

Thanks!
