### ISSUE TITLE
Route map sometimes loads without KML or is blank altogether

### ISSUE THREAD

**Issue by sherson** [umts/pvta-multiplatform#146]
Sometimes the route map is blank, or the map, buses, and location are plotted without the KML. 

Clearing my cache didn't do anything. Seems to be happening only on my computer, but in multiple browsers: Chrome and Safari (as well as Chrome incognito):

<img width="1353" alt="safari map no kml" src="https://cloud.githubusercontent.com/assets/409008/14464363/867c3930-009c-11e6-8f6a-6ed5d3e32217.png">

<img width="1279" alt="chrome icognito no kml" src="https://cloud.githubusercontent.com/assets/409008/14464362/867ac294-009c-11e6-989d-a20778a53cec.png">

<img width="1242" alt="chrome no map" src="https://cloud.githubusercontent.com/assets/409008/14464420/bc2e7a52-009c-11e6-9935-537fb9a17466.png">

Most of this is irrelevant, but copied for reference:

| where | what |
| --- | --- |
| umts.github.io/:18 | GET http://umts.github.io/pvta-multiplatform/cordova.js |
| ng-cordova.js:3320 | get CurrentPosition() and watchPosition() are deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details. |
| ionic.bundle.js:16358 | SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead. |
| services.js:469 | localforage routes saving error: DataCloneError: Failed to execute 'put' on 'IDBObjectStore': An object could not be cloned. |
| util.js:220 | Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required |
| ionic.bundle.js:23694 | OPTIONS http://bustracker.pvta.com/infopoint/rest/routedetails/get (anonymous function) @ ionic.bundle.js:23694sendReq @ ionic.bundle.js:23513serverRequest @ ionic.bundle.js:23225processQueue @ ionic.bundle.js:27747(anonymous function) @ ionic.bundle.js:27763Scope.$eval @ ionic.bundle.js:29026Scope.$digest @ ionic.bundle.js:28837Scope.$apply @ ionic.bundle.js:29131done @ ionic.bundle.js:23544completeRequest @ ionic.bundle.js:23716requestLoaded @ ionic.bundle.js:23657 |
| /pvta-multiplatform/#/app/routes/10003:1 | XMLHttpRequest cannot load http://bustracker.pvta.com/infopoint/rest/routedetails/get. Response for preflight has invalid HTTP status code 404 |

```
```

**Comment by akaplo** [comment]
Is it just sometimes?  What steps cause it? I'm trying it and can't reproduce it

**Comment by sherson** [comment]
It has been happening for me since last night. It's mostly consistent... Once in a while, when I load a route that I haven't loaded before, the KML appears. Then I reload that page, and it breaks (either doesn't load the map at all or loads everything but the KML). 

But usually when I load a route that (I think) I haven't loaded before, it doesn't work. Since last night, it hasn't displayed the KML of any route that I loaded before (I think).

Restarting the browsers doesn't help.

It seems to be just my computer, though I haven't noticed any issues with other websites. 

Will demonstrate it for you tomorrow if it's still misbehaving.

**Comment by sherson** [comment]
Due to #124
