### ISSUE TITLE
Disclaimers

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#147]
I think it might be a good idea to add a few disclaimers to the app now that real people that we've never met before might be using it.

I can think of two important ones; does anyone have any to add?
1. Beta disclaimer - "this app is in beta"
2. Realtime disclaimer - something along the lines of "The realtime data provided is courtesy of Availtec's radio systems. The PVTA cannot assure that the data is correct and it should be used with caution."

**Comment by bgregg** [comment]
Also putting feedback on the home page. Working on this now.

**Comment by werebus** [comment]
I don't know if we should throw Avail quite so far under the bus (as it were).  Something a little more general about real-time estimates being a an _estimate_ and not always available should be fine.

@sherson, thoughts?

**Comment by bgregg** [comment]
See #149

**Comment by sherson** [comment]
Yep, my inclination is to be less specific. Perhaps something to the effect of?:

> This app is a beta; both it and the realtime data are being tested. Please double-check its results with PVTA [schedules](http://www.pvta.com/mobile/schedules.php). Report any issues to programmers@admin.umass.edu.
