### ISSUE TITLE
Map bus icons

### ISSUE THREAD

**Issue by sherson** [umts/pvta-multiplatform#148]
Would be good if the map bus icons look like buses, are the color of the route, and have indicators showing direction.

**Comment by werebus** [comment]
Cursory Google search:

http://map-icons.com/

They extend `google.maps.Marker` to allow SVG icons (which are style-able) so color is easy.  Direction's a bit harder, but SVGs can be composed of multiple paths, so if the indicators were available as paths elsewhere in the page you might be able to [`<use>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use) them in a composite-icon-type-thing :question:

**Comment by sherson** [comment]
Looks good:

<img width="219" alt="bus-station.svg" src="https://cloud.githubusercontent.com/assets/409008/14566369/511c370a-02fd-11e6-9563-f53963f4537b.png">

**Comment by werebus** [comment]
Also, you can apparently use SVG paths as the "Symbol" on a map icon using the native Google API: https://developers.google.com/maps/documentation/javascript/markers#symbols Although documentation is sparse.

**Comment by akaplo** [comment]
Looks like this is finally going to happen.  I managed to take the simplest path (:trollface:) possible - hardcoding the well-known SVG path for "Bus" with decent results.  My one question: for direction, we can use the `Heading` property from Avail's `vehicle` object for something like the following:

![image](https://cloud.githubusercontent.com/assets/7144148/20087076/626ba278-a543-11e6-8995-4b2b0b1d7e6c.png)

It's almost stupidly intuitive, but I'm not sure I like it.  

Here's an example of a 39 headed toward HC:
![image](https://cloud.githubusercontent.com/assets/7144148/20087023/d8b7a91e-a542-11e6-900f-27c3feff9a7f.png)

Yet another example: two 30s, one approaching Puffton and one on Rt 9 near Rolling Green headed out:

![image](https://cloud.githubusercontent.com/assets/7144148/20087045/212a3734-a543-11e6-8968-734f6e3a159a.png)

API-wise, there are a few good Fiddle examples linked to in [this stackoverflow article](http://stackoverflow.com/questions/24413766/how-to-use-svg-markers-in-google-maps-api-v3)

 @sherson @werebus Thoughts?

**Comment by sherson** [comment]
Hmmm... I like it, but something about it seems a bit weird.

Upright bus icons with a little rotated arrow/triangle indicating direction (or rotated buses with a rotated arrow/triangle) would be better, I think. 

Still, as is, it's a step up from the default location pins.

**Comment by sherson** [comment]
Also, that's just my first impression. After writing that comment, I looked again and my second impression is that it's simple and effective as is. 

So I think it's fine to implement. Also, despite the vague, knee jerk weird feeling mentioned above, it looks good, in my opinion.

**Comment by werebus** [comment]
Yeah, my first impression was that it was a little goofy looking.  It does communicate the piece of information you're trying to get across, though.  I'd say go with it and work on something a bit more nuanced later.

**Comment by akaplo** [comment]
Goofy is exactly the word I'd use, as well as deceptively simple. I will finish implementing.  This is actually a good setup for #226.
