### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by bgregg** [umts/pvta-multiplatform#150]
SInce we are using Google Analytics we need to have a privacy policy in order to tell people that we are collecting data about their usage of the app.

**Comment by akaplo** [comment]
@bgregg did this already happen?  I recall @werebus saying he looked distantly at a draft you presented to him and the conversation hasn't continued since then.

**Comment by bgregg** [comment]
@werebus had asked for some time to look at, and I havent heard from him since. I will check in with him today.

**Comment by akaplo** [comment]
Time to just throw something up there.
