### ISSUE TITLE
Remove API Keys From Source Code

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#156]
Half-mentioned by @werebus in a comment on #152.  The version currently on master does (but should not) have the key for the Maps Javascript API in index.html.  That can be easily removed, but my question pertains more to the version on gh-pages.

Since the version there is exactly what's being seen when someone navigates to a page, don't we have to keep it in the source code (even if just for that branch)?  As of this week, there are in fact 2 API keys; one on master (and everything that has pulled or branched from master since then) for development and one on gh-pages for "production."

**Comment by akaplo** [comment]
Cannot obscure API keys in an entirely frontend app, especially when it's being hosted on gh-pages.

**Comment by werebus** [comment]
@akaplo and I were looking at this just now.  In the Google API console, we _can_ put restrictions on what clients can use a key: 
-  For web sites, you can require a particular `HTTP_REFERER`,
-  For android apps, you can require the app be signed with a particular key
-  For iOS apps, you can require a particular app identifier.

That said, putting these restrictions in place will likely interfere with the existing APKs that are out there.  This can be done at a later date if it comes up.
