### ISSUE TITLE
Nearest Stops

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#16]
Like BusInfoBoard, we should use the $location service to get and populate a list of the ~3 <b>nearest stops</b> to the user.

This'd likely be similar to what we're already doing in the MapController when we get current location, but we'd need to parse the list of stops and compare lat/long to find the closest ones.  BusInfoBoard's code may function for this...we could just steal it?

**Comment by petermarathas** [comment]
Does BusInfoBoard do this? If I remember correctly, it takes the desired stops as parameters in the URL and doesn't use the user's location at all. 

I'll start working on this. I think the best way to do this once we find out how to calculate distance is to order the stops on the Stops page by distance from the user.

Another idea if we don't want to calculate the distance from every stop is to start the user off with a map showing current location, and then marking on the map the nearby stops.

**Comment by werebus** [comment]
Yeah, the 'stop selector' page does.

https://github.com/umts/BusInfoBoard/blob/master/StopSelector/js/main.js#L136-L145
