### ISSUE TITLE
Time Picker Should Untoggle ASAP When Clicked

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#193]
On Plan Trip, if ASAP is toggled on when the date/time picker is clicked, it won't let you pick a time.  Attempting to type in a time or select a date will immediately fail, as the system will clear out your entry and set it to Date.now().

We should turn off ASAP when we sense that the user is attempting to select a date/time.

**Comment by petermarathas** [comment]
Clicking the datepicker should toggle ASAP off, but if it's not working on your machine then something is wrong 😨

**Comment by akaplo** [comment]
This is actually my bad.  I was using the version that was deployed to gh-pages when I opened this issue, not the version on master. It works fine.  Oopsie!
