### ISSUE TITLE
Data Usage Saving

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#2]
Currently, when anyone views a page that contains Avail data, that data is redownloaded.

<b>example</b>: you search for Arnold House, view its Stop Departures for a minute, then go look at where the buses on NA/BR are currently located, and then go back to view Arnold House's Stop Departures.

At the time of this writing, this sequence contains the following data requests:
1. The list of ALL Stops and Routes
2. Stop Departures for Arnold House (2x, because it auto-refreshes every 30 seconds)
3. Stop data for Arnold House (because Stop Departures don't include the name)
4. The list of routes (or the list of EVERYTHING, if you're doing a full search)
5. The Route Details for the route 30
6. Stop Departures for Arnold House

Combined, this approaches 1MB of data, which is devastating for mobile users.  Since this is a mobile app, something must change before deployment.

<b>Cordova</b> has documentation on how to save data downloaded from the internet into the database that all mobile devices support for apps.  Thus, when we download static data (ie the list of stops and routes), we can save it, timestamp it, and retrieve it all later when we need it.  If the timestamp is expired, it should downloaded again to ensure that the user has the current data.

This, I believe, is the end-all answer to this issue.

A quicker, less sustainable answer is to create an object for every item we want to download and save that object in a centralized service that is destroyed upon each exit from the app.  This will work, but still causes more downloads than the above option, and also requires us to maintain the data structures and facilitate the passing of data.  

Cordova's library should abstract away the passing and handling to the extent that it is almost trivial.  

<b>Note</b> that we cannot store all information.  Stop Departures, Vehicle details (which includes Locations), and RouteDetails (which includes a list of current Vehicles and their respective Locations), change every time a bus accelerates.  

Thus, the only static data is the list of Stops and the list of Routes.  That's not a huge data savings, but it's a start.  Going forward, we can (and should) include the PDF schedules for each route, and the Cordova library will allow us to package them with the app, redownload them, and save them once we determine them to be obsolete.

**Comment by dfaulken** [comment]
For ~~'static' data like routes and stops~~ the schedule PDFs, it'd be nice if we didn't have to manually push out updates - we already have a few sub-tasks dependent on Hastus changes. Maybe a middle ground - ~~pull just once a day~~ specify some dates on which we know new schedules will be published?

**Comment by werebus** [comment]
I believe @akaplo was suggesting that the app would be responsible for that.  That is, if the the stop list was more than, for example, 14 days old it would re-fetch it from Infopoint.

**Comment by dfaulken** [comment]
Do we always push out schedule changes >14 days in advance?

**Comment by werebus** [comment]
Welp, hard to say, but herein you are describing the general problem with caching.

If we had control over the server-side of things (hah) we would be able to specify `Last-Modified` or `ETag` headers and then use `HEAD` requests.  As it stands, InfoPoint "says" via its headers that we should never cache its data:

```
$ http HEAD http://bustracker.pvta.com/InfoPoint/rest/stops/getallstops

HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Wed, 20 Jan 2016 22:52:46 GMT
Expires: -1
Pragma: no-cache
Server: Microsoft-IIS/8.5
Transfer-Encoding: chunked
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
X-UA_Compatible: IE-10
```

**Comment by akaplo** [comment]
I agree with all of this.  Interestingly, there is an endpoint for 'static' data:

http://bustracker.pvta.com/InfoPoint/rest/staticdata/getallstaticdata

which, also interestingly, is just the list of Visible Routes.  So, at the very least, I'd say Avail "supports" caching of these data, if nothing else.

@werebus was right about what I meant, and @dfaulken has a good point about the schedules.  

I'd say we shouldn't trust us/Hastus/Avail to provide the info far enough in advance, so I'd elect to have the app timestamp downloads of this type of data when putting them into the database and set expiration dates based on the data type (i.e. <b>1 week for schedules, 2 weeks for routes, and 2 weeks for stops</b>?).

**Comment by akaplo** [comment]
Closing this in favor of some variant of #9 being implemented.  This was first partially handled in #22, and these additions have since been tweaked in various PRs.  More modular issues may be opened in the future related to this, but I believe, as a whole, it can be closed.
