### ISSUE TITLE
Add easier way for adding things to favorites

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#209]
On My Buses, when you click the big ➕ to add a route or stop to favorites, it just redirects to Routes and Stops and then you have to click on one, be taken to its page, and then add it to favorites. This should be easier.

**Comment by akaplo** [comment]
We already show when a route/stop is favorited in its list entry.  

Maybe, for each entry, we expand this to work the same way that the heart does in the Route/Stop pages themselves (an outlined heart vs filled in heart; clicking triggers function that toggles favorite).

Perhaps a slide-over feature (to reveal the "favorite this thing" functionality) is a better idea. 

Perhaps we do a popup menu when the user long-presses on an entry.

Thoughts?

**Comment by akaplo** [comment]
@bgregg I think this could be a fun issue for you.

**Comment by bgregg** [comment]
I like the first thing you said. An outlined heart vs a filled in heart and if you click it it toggles that feature, click anywhere else in the row and it redirects you to that route/stop

**Comment by akaplo** [comment]
Sounds good.  Perhaps you could make directives (like I'm currently doing on the `vehicle-ui` branch) for `routes` and `stops` so that you can reuse this on `Routes and Stops` **and** `My Buses`.

**Comment by akaplo** [comment]
@bgregg how's this coming?

**Comment by bgregg** [comment]
This is almost there, should be done today or tomorrow
