### ISSUE TITLE
Add a way to reorder stop and route lists

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#210]
In Routes and Stops, we should add a way to reorder the lists if the user so wishes.  Now that we display when an entry is a favorite, it might be nice to have all the favorites appear at the stop, but this isn't necessarily the way it should always be, so giving that option would be nice.

Options I can think of to put in the "order by" include:
1. Favorited?
2. Alphabetical
3. By Location (for stops only (routes would also be cool, but how?))

**Comment by akaplo** [comment]
(I have started work on this, but it's taken a back seat.  If anyone wishes to take it on, there's a branch.  Be my guest.)

**Comment by akaplo** [comment]
I think @bgregg is rolling this into a combined PR with #209, am I correct?

**Comment by sherson** [comment]
Should also allow users to order routes in "My Buses" and/or order them by `<RouteAbbreviation>` (loosely related to #225).
