### ISSUE TITLE
Add More Specific Edt/Sdt Times in Stop

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#215]
Perhaps clicking a stop departure could expand it and provide info that's more specific than "in an hour."  Requested by @dfaulken.  

The expand-ey feature (like how clicking on a route expands into a list of departures) is not an integral part of this issue; figuring out a good way to give more specific times is the goal.  If we decide this means removing the "in an hour" and replacing it with "in 56 minutes," that'd be fine.

**Comment by dfaulken** [comment]
Sure, I would also include the actual time - say `3:12 pm (in 32 minutes)`.

**Comment by petermarathas** [comment]
I agree with Dave, here's how it would look

![screen shot 2016-09-22 at 5 06 51 pm](https://cloud.githubusercontent.com/assets/6088239/18766376/f67897bc-80e7-11e6-8775-1374fd28217c.png)

**Comment by akaplo** [comment]
Definitely like that.
