### ISSUE TITLE
Roll Vehicle Page Into Route Page

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#219]
Eliminate the Vehicle page.  

I was starting to redo it (see below for a work-in-progress screenshot), but maybe we can just put the extra details into the Vehicle portion of the Route page (perhaps making it expandable, like how each route expands into departure details in Stop).  

Each entry for a vehicle would include a button to map it and its details, of which there aren't really enough to dedicate an entire page in our view hierarchy to.

I'm interested in thoughts.  @sherson, @werebus, @bgregg , and @petermarathas, what do you all think?

This issue would encompass #155.

The old vehicle page vs the new one:

**New:**
<img width="493" alt="screen shot 2016-09-20 at 1 27 59 pm" src="https://cloud.githubusercontent.com/assets/7144148/18681747/614fd7f6-7f37-11e6-9777-b0d6c12a1a74.png">

**Old:**
<img width="489" alt="screen shot 2016-09-20 at 1 36 57 pm" src="https://cloud.githubusercontent.com/assets/7144148/18681761/6b137536-7f37-11e6-9787-ec505209b43d.png">

**Comment by werebus** [comment]
Yeah, I  don't think per-vehicle pages are of very much use or interest to anyone but Transit employees.

**Comment by petermarathas** [comment]
I agree. Also, knowing how many people are on a bus is awesome.

**Comment by sherson** [comment]
I also agree.

However, currently when a user taps on a departure on a [Route page](https://umts.github.io/pvta-multiplatform/#/app/routes/20030), they see [vehicle details](https://umts.github.io/pvta-multiplatform/#/app/vehicles/89/20030).

While the new screenshot shows a different title, formatting, and additional fields (`Currently on the [route]` and `[x] passengers are riding this bus`), it's still a screen with a bunch of per-vehicle details, and it's unclear (to me) how the proposed flow differs significantly (apart from it maybe being expandable).

**Comment by werebus** [comment]
@akaplo said above, "I was starting to redo it ... but maybe we can just put the extra details into the Vehicle portion of the Route page"

The screenshots are of the "redo(ing) it".

**Comment by sherson** [comment]
Ah yes. 

OK, if we eliminate unit, the route page would have the 3 current fields (status, headed toward, last stop) plus `[x] passengers are riding this bus` and `bus [number]`. That might look good.

**Comment by werebus** [comment]
:+1: "Unit" is especially lose-able. I'm on the fence on bus number. It's slightly useful in that it's printed a few extra places on the bus you might be looking for (where you might not be able to see one of the destination signs), but it can also change without notice (bus swaps).

**Comment by akaplo** [comment]
All good points, and agreed.  I'll get started on this soon.

**Comment by akaplo** [comment]
Closed #155, as this is overtaking it.

**Comment by akaplo** [comment]
<img width="502" alt="screen shot 2016-09-21 at 1 16 59 pm" src="https://cloud.githubusercontent.com/assets/7144148/18721308/d7d1a58c-7ffd-11e6-8d34-7b7a8aee3bb6.png">
How's this looking?  It's a work in progress, but I think it's close.

**Comment by werebus** [comment]
Two thoughts
1.  The "30" seems a little redundant on each card.
2.  Is a red clock late or early?

**Comment by akaplo** [comment]
1. I suppose you're right.  I'll move it above and repost.
2. Red clock is late...I had the word "late" but I decided it was self-explanatory.  You disagree?

**Comment by werebus** [comment]
The route number is already two other places above the list, right?

So, what does an early bus look like?

**Comment by akaplo** [comment]
Does Avail have a DisplayStatus for early?  I've never seen one.

**Comment by akaplo** [comment]
Here's an update with @sherson's input.

<img width="503" alt="screen shot 2016-09-21 at 6 37 55 pm" src="https://cloud.githubusercontent.com/assets/7144148/18731561/9e125fee-802a-11e6-8163-31a9e760f73a.png">

**Comment by petermarathas** [comment]
I think an icon that shows up when the bus is bendy would be helpful.
