### ISSUE TITLE
Possible future tweaks to Routes page (remove individual bus maps, re-format)

### ISSUE THREAD

**Issue by sherson** [umts/pvta-multiplatform#222]
Once we have directional bus icons (#148), we can simplify the route page further (#219) by removing the map(s) for the individual bus(es). Perhaps we could also remove the `Map This Route` footer, and instead have a `Map` button for the route in the header (next to the heart).

At that point, the routes list might look better as:

```
To Destination                     Status
[location icon] LastStop       [x] Riders
```

(since we can then allocate more of the width to the first column)

**Comment by akaplo** [comment]
Dependent on #148.

**Comment by akaplo** [comment]
Why is this still open?  This issue asks for a map icon in the Route header, and map icon removal from the bus list.
As of right now, we have that. Am I missing something?
![image](https://cloud.githubusercontent.com/assets/7144148/21375460/b2fd4532-c6fb-11e6-8f29-eb70d1927020.png)

**Comment by sherson** [comment]
yep, all set
