### ISSUE TITLE
Add a welcome popup for first time visitors

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#224]
I think we should give a one-time popup to explain a little about the app - the what, why, and how should be enough to get new users off the ground.

I think this is pertinent especially now, since people going to m.pvta.com might be surprised at the lack of businfoboard...50% of our traffic today came from m.pvta.com.

@sherson @werebus thoughts?

**Comment by sherson** [comment]
I think the app is pretty self-explanatory, and the UI is streamlined (there are only so many things to tap/click on). I don't see this as a big problem.

But there's no harm in adding a 'How to use this app' link to the current welcome message, and/or a one-time pop-up as you suggested.

**Comment by akaplo** [comment]
Closed by pushing to master by mistake, see [commit 1](https://github.com/umts/pvta-multiplatform/commit/5d2677a0c6ff6940063368ce58ebc04a310271b2) and [commit 2](https://github.com/umts/pvta-multiplatform/commit/e8eee5135a36ad7df3d93c83fca676bda7ae03a5)  for more info.
