### ISSUE TITLE
Use RouteAbbreviation instead of ShortName?

### ISSUE THREAD

**Issue by sherson** [umts/pvta-multiplatform#225]
Perhaps we should switch to using `<RouteAbbreviation>` instead of `<ShortName>`? We're currently using names that the public might not be familiar with. For example:

| short name | common name |
| --- | --- |
| 914 | R14E |
| 920 | P20E |
| 921 | P21E |
| R52 | TT |

RouteAbbreviation is used at https://bustracker.pvta.com.

This came up while looking at #220.

**Comment by akaplo** [comment]
Should be a 60-second fix.
