### ISSUE TITLE
App Store / Play Store Accounts

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#230]
I'm creating an issue for this so that we can track any steps being taken towards obtaining developer accounts on the [App Store (Apple Dev Program Enrollment Page)](https://developer.apple.com/programs/enroll/) ($99) and [Play Store (Google Developer Enrollment Page)](https://play.google.com/apps/publish/signup/) ($25).

The money could come from a few possible places
- PVTA
- University of Massachusetts
- UMass Transit (i.e. budget or procard?)
- Us (devs)
- Kickstarter

I'm assigning @sherson to this, because he will likely be one to resolve it.

**Comment by sherson** [comment]
Will remind PVTA about it.

**Comment by sherson** [comment]
Reminded PVTA a few times over the last month, and was told this has been approved. I emailed PVTA another reminder today.

**Comment by akaplo** [comment]
Updating for the sake of a paper trail:  A/O today, PVTA says they have obtained Play Store credentials (UMTS does not have possession yet) but also that they are facing a legal roadblock regarding App Store credentials.

**Comment by sherson** [comment]
Talked to PVTA again regarding the (frustrating) delay. They had run into an issue, and this has been handed off to someone else there to finish up, but should (hopefully) be nearing completion.

**Comment by akaplo** [comment]
Did they give any semblance of a timeline? I recall we gave them a "deadline" of Thanksgiving.

**Comment by sherson** [comment]
Nothing specific, but I'll try to contact the other person today. You'll know when I know.

**Comment by sherson** [comment]
FYI, @werebus, @dfaulken, and I successfully logged into the [Google Play Developers Console](https://play.google.com/apps/publish).

**Comment by akaplo** [comment]
As have I!

**Comment by akaplo** [comment]
I think it's reasonable that I close this issue.  Thanks @sherson for your perseverance in pushing it though!!

**Comment by sherson** [comment]
I was going to leave it open until we're in the Apple Developer Program, but we don't really need an issue for this, so that's fine (I'll keep asking about it).

**Comment by akaplo** [comment]
Lol I totally forgot about that because I was so excited.

**Comment by akaplo** [comment]
Paper trail update: still waiting on iOS.  Stable 1.0 released on Android on December 31st, 2016. 🎊

**Comment by sherson** [comment]
I pinged PVTA about it.

**Comment by sherson** [comment]
There was some progress with iOS, but Apple rejected the enrollment. PVTA is sorting it out.

**Comment by akaplo** [comment]
Enrollment is pending once more.

**Comment by akaplo** [comment]
Enrollment accepted, now it wants a credit card. PVTA IT has been notified.

**Comment by akaplo** [comment]
Access to iTunes Connect has been obtained, and a beta has been uploaded for Apple's final review before publishing.  We officially have full-fledged App Store credentials as of 5/9/17.

Thanks to @sherson for his persistence and hard work!
