### ISSUE TITLE
Marketing Materials For UMTS Buses

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#231]
When we release, we should put flyers on our buses so that passengers can learn of the app.

If anyone is into designing these kinds of things, feel free to take it on.  If none of us can/want to, @sherson, is it reasonable to ask the UMTS marketing coordinator to help?

**Comment by sherson** [comment]
Sure, I'll ask Glenn and Seritta about.

**Comment by sherson** [comment]
Glenn gave this a thumbs up, and Seritta will do it. Leaving this open until it happens.

**Comment by akaplo** [comment]
@sherson heard there's been some progress on this?

**Comment by sherson** [comment]
I emailed Seritta about how this is going.

**Comment by sherson** [comment]
I was told posters should be up by the end of the week.

**Comment by sherson** [comment]
Decided to hold off because we hope we're close to launching as Android and iOS apps #230.

**Comment by akaplo** [comment]
Hibernating until #230 is closed.

**Comment by akaplo** [comment]
Barring any miracles, pvtrack won't release on iOS before @petermarathas and I graduate.

@sherson, any chance we can move forward with announcements on our buses? I'd like passengers to start hearing about the app before graduation.  I'm fine with flyers that list `Play Store` and `m.pvta.com` and say "iOS coming soon" (we can put out new posters in December, when an iOS release drops :man_facepalming:).

**Comment by sherson** [comment]
Emailed Seritta about it (CCd @akaplo).

**Comment by akaplo** [comment]
The poster will go up very soon, and will look very close to this (with one or two final tweaks).

![image](https://cloud.githubusercontent.com/assets/7144148/24917816/582e7690-1eac-11e7-9e46-de9999bfb132.png)

**Comment by werebus** [comment]
What does that asterisk go to?

**Comment by akaplo** [comment]
That was the fix that's since been made - the actual printed version says 
>*iOS coming soon

**Comment by sherson** [comment]
I'm pretty sure I suggested to Seritta that she replace the * with iOS, but [whatever](http://bikeshed.org/).

**Comment by werebus** [comment]
Yeah, I just have an OCD-ish objections to when there are a number of asterisks that is not a multiple of 2.

**Comment by akaplo** [comment]
Merf. They're already printed and I don't feel like making her change it (you guys are welcome to, though!).

![image](https://cloud.githubusercontent.com/assets/7144148/24973064/7291726e-1f8b-11e7-8361-796d40b75fa7.png)

**Comment by sherson** [comment]
Seritta said they were put on the buses yesterday.

**Comment by akaplo** [comment]
FWIW @werebus there are no longer any asterisks.
