### ISSUE TITLE
Routes sorting messed up after reload

### ISSUE THREAD

**Issue by sherson** [umts/pvta-multiplatform#243]
Routes appear to be sorted by `<RouteAbbreviation>` when the user first loads the [Routes list](https://umts.github.io/pvta-multiplatform/#/app/routes-and-stops/0), however, after reloading that page, or going to a route and back to the routes list, it's sorted by `<ShortName>`. 

See #225 (also loosely related to #210).

**Comment by akaplo** [comment]
Will wait until after the Routes list updated are merged via #209 and #210.

**Comment by akaplo** [comment]
A fix for this is included in #272.

**Comment by akaplo** [comment]
I believe this is now resolved. I still have never run into this problem, but #272 adds explicitly forcing sorting by `RouteAbbreviation`.  @sherson let me know if you still encounter this and we can reopen and look more closely.

**Comment by sherson** [comment]
Great, thanks.
