### ISSUE TITLE
Display stop departures per route per direction

### ISSUE THREAD

**Issue by sherson** [umts/pvta-multiplatform#246]
Like businfoboard (so, for example, OH and MC buses show up separately)

https://umts.github.io/pvta-multiplatform/#/app/stops/58
http://umts.github.io/BusInfoBoard/?stops=58

<img width="559" alt="multiplatform-stop58" src="https://cloud.githubusercontent.com/assets/409008/19724220/157d8972-9b4d-11e6-9cc2-6e73e5e09594.png">

<img width="685" alt="businfoboard-stop58" src="https://cloud.githubusercontent.com/assets/409008/19724222/19bdfdf0-9b4d-11e6-9aa6-779070c6660d.png">

**Comment by akaplo** [comment]
@sherson Just had a few non-bus people suggest to me that we give the option of sorting all departures at a stop by **time**, as many passengers might not care what departure is next for a given _route_, but what departure is next _in general_.

Thoughts?  I think an option to sort by route or time is a good idea.

**Comment by sherson** [comment]
There are pros and cons to each sort, so good idea.

Side note: that was actually [the first issue created for BusInfoBoard](https://github.com/umts/BusInfoBoard/issues/1) (which allows it via query string).

![little-known-fact](https://cloud.githubusercontent.com/assets/409008/19962055/3d94d682-a18c-11e6-84f6-055f096add71.png)

**Comment by akaplo** [comment]
Should be able to bang the rest of this out tomrrow.
