### ISSUE TITLE
Schedule: Can't change time when searching

### ISSUE THREAD

**Issue by sherson** [umts/pvta-multiplatform#257]
Tapping on `Leaving Now` (next to `Search for buses:`) doesn't do anything in Chrome in Android. Works fine on Chrome in OSX.

**Comment by sherson** [comment]
More information:

This behavior was reproduced on multiple devices. The problem exists with Chrome and Firefox for Android. It sometimes works if the user taps in a rather narrow spot (on the right edge of the screen just above the `Departing At...` triangle and below the `Enter a destination` field). 

Tapping on `Leaving Now` using Chrome for iOS or Samsung's stock Internet browser seems to work fine.

**Comment by akaplo** [comment]
Closed via #259 (Ionic bug related to Chrome 52; Ionic was updated to resolve it, see their [release notes](https://github.com/driftyco/ionic/releases/tag/v1.3.2)).
