### ISSUE TITLE
Screenreaders Can't See Back Button

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#262]
Should probably make it so screen readers can give the option of going back.

https://docs.google.com/document/d/1YCbIRPXAtBY0PftbALOMGl6bn31qiAY_l867xDUKsiU/edit?ts=581cd8cf

**Comment by akaplo** [comment]
@petermarathas was this fixed in #317? I believe so.

**Comment by petermarathas** [comment]
I think so too. Going with yes.
