### ISSUE TITLE
Users No Longer Can Retrieve Current Location

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#267]
@sherson @werebus @petermarathas @bgregg @dfaulken I need everyone's thoughts on this.  Since we switched the DNS records and became `m.pvta.com`, we've had to serve over `HTTP` instead of `HTTPS`.  

Majors browsers **disallow location services to be requested** by sites served over `HTTP`, so this will cause many of our users to be unable to use some of our key features.

Should we:
- switch the DNS record back and use GH-pages to serve HTTPS?
- ~~Get an SSL certificate, figure out how to make it work on gh-pages, and continue serving here?~~
- Switch hosting providers, get an SSL cert, and serve there?
- Stop hosting a web-app and make it a mobile app _only_ after #230 is resolved?
- Remove location features from the app?

![image](https://cloud.githubusercontent.com/assets/7144148/20361266/efb667d6-ac04-11e6-8660-b0340daf96fa.png)

**Comment by dfaulken** [comment]
My question is: why does m.pvta.com not simply serve SSL?

**Comment by werebus** [comment]
Because m.pvta.com is a server (or servers) in GitHub's datacenter, and they don't support SSL for domains that aren't *.github.com and *.github.io because doing so would require them to have the private key (and DCV process) for each domain.

**Comment by werebus** [comment]
This one, I think:

>  Switch hosting providers, get an SSL cert, and serve there?

**Comment by akaplo** [comment]
The effects of this have been slightly mitigated by #278, but I'm leaving it open.

**Comment by akaplo** [comment]
For the sake of a paper trail: a/o 12/5/16, @werebus is planning to get us off gh-pages and obtain an SSL cert, as noted above.

**Comment by akaplo** [comment]
![image](https://cloud.githubusercontent.com/assets/7144148/21375378/189ac3b6-c6fb-11e6-811c-169eb5597985.png)

**Comment by werebus** [comment]
All set
