### ISSUE TITLE
Route With Only Past StopDepartures Still Appears

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#274]
Time of screenshot: 12:42AM on a Thursday:
![image](https://cloud.githubusercontent.com/assets/7144148/20783029/fe8933b4-b75e-11e6-9239-0f1419d30dfa.png)
Odd, since the last B43 at Amherst College is scheduled at 12:15AM.

From the Avail feed, also at 12:42AM:
![image](https://cloud.githubusercontent.com/assets/7144148/20783270/bcb757b6-b760-11e6-9d89-242122f9f060.png)

The date highlighted above corresponds to (screenshot also at 12:42AM):
![image](https://cloud.githubusercontent.com/assets/7144148/20783064/404cf1d2-b75f-11e6-95dd-16aaa2fbe403.png)

This looks like a standard case of bad code design on my part.

**Even though the Route has no _valid_ departures, we still download the details for the route and attempt to display it on the page.**  This is likely because it [has departures and is supposedly not "Done"](https://github.com/umts/pvta-multiplatform/blob/master/www/pages/stop/stop-controller.js#L84) 

Logically, asking PVTrack for departures by Time instead of by Route doesn't have this issue, because it only loops through _valid departures_, not route directions:
![image](https://cloud.githubusercontent.com/assets/7144148/20783149/e51ac608-b75f-11e6-8f5d-b19660d76243.png)

So, there is no loss of information occurring here, just confusion for the user. But still bad.

One last thing: the root of this issue occurring in the feed seems to be due to the one B43 still out being on the wrong trip.  I've been watching that bus for 20 minutes, and it's definitely not headed toward Amherst.  Perhaps worth forwarding to Avail, @sherson, or just driver error?
![image](https://cloud.githubusercontent.com/assets/7144148/20783191/313d0514-b760-11e6-84f4-d22929f8a16e.png)

**Comment by sherson** [comment]
I referenced this in an existing issue about buses being on the wrong trip, and also opened an issue about  `<LastStop>` being `City Line I`, which isn't a real stop (it seems that field includes non-public stops).
