### ISSUE TITLE
Display <LastUpdated> for user

### ISSUE THREAD

**Issue by sherson** [umts/pvta-multiplatform#279]
We should display `<LastUpdated>` so that users know the age of a bus location.

For purposes of comparison:

![pvta-bus-tracker-vehicle](https://cloud.githubusercontent.com/assets/409008/20840345/ed1211e4-b87d-11e6-880c-d019acab97b9.png)

![pvtrack-vehicle](https://cloud.githubusercontent.com/assets/409008/20840349/efe35c70-b87d-11e6-869f-67a97374dfcc.png)

**Comment by akaplo** [comment]
Bundling into a PR with #280.
