### ISSUE TITLE
Popup Telling Users Android App is Available

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#283]
When we ship 1.0, I think we should have a popup for browser users at m.pvta.com to tell them we have a native app available on the Play Store, and that an iOS app is forthcoming.  This popup need only appear once per user.

**Comment by werebus** [comment]
Mmmm...

Nothing I like better than I website that tells me, "I know you're already here, but would you like to go somewhere else that has the same information, but first you have to install an app?"

**Comment by akaplo** [comment]
Maybe, then, replace the "This is a beta" bar on My Buses with a "Go get the real app" bar?

**Comment by sherson** [comment]
This came up in a discussion today... my opinion:

I'd rather it be mentioned somewhere in the app without being obtrusive. If being in `Settings` > `About` is too buried, perhaps there could be another item listed in the menu below `Settings`. I think a bar at the top of the main screen or a pop-up would be annoying.

**Comment by akaplo** [comment]
I was bored tonight and implemented this, which I set to appear everywhere other than when run _natively_ on Android (i.e. it will appear on mobile Chrome on Android).  Thoughts?

A very obv macOS screenshot:
![image](https://cloud.githubusercontent.com/assets/7144148/22580477/be90ffd8-e9a6-11e6-83f6-52fda469c0bc.png)

A very obv Android Chrome screenshot (pardon my 12:30am screenfilter):
![image](https://cloud.githubusercontent.com/assets/7144148/22580501/e7c4d1c2-e9a6-11e6-8049-3c9faf4b2da7.png)

A screenshot would be redundant, but the same code bundled and run natively on my personal Android phone produces the expected behavior.

**Comment by sherson** [comment]
Just to confirm, it would still only appear once per user?

**Comment by akaplo** [comment]
That's minimally intrusive enough that I'd just leave it there and eventually remove it with another update.  For that amount of intrusiveness, I wouldn't expect users to even see it the first few times they use the app while it's there.

**Comment by akaplo** [comment]
I believe @sherson, @werebus, and I spoke in person on Friday.  I'm working on an even more non-intrusive version that appears at the bottom of the sidemenu as opposed to an entire entry.  

Screenshots to follow soon.

**Comment by akaplo** [comment]
Here's what I came up with. Thoughts?

![image](https://cloud.githubusercontent.com/assets/7144148/22793619/5ade578e-eebe-11e6-85bb-1fa7b8ab64b3.png)

![image](https://cloud.githubusercontent.com/assets/7144148/22793743/baf33eaa-eebe-11e6-9eec-a45067c432dd.png)

**Comment by sherson** [comment]
👍

**Comment by werebus** [comment]
Here's a question. Should we do this instead?

https://developers.google.com/web/fundamentals/engage-and-retain/app-install-banners/

And does Apple have something similar?

**Comment by akaplo** [comment]
Quick glance tells me the only thing in the production app stopping this
from existing automatically is the service worker requirement.

Will look into more detail.

**Comment by akaplo** [comment]
The Safari equivalent for iOS - https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html

FYI, there is no Firefox equivalent that I can find (branch.io is 3rd party service that might work, but 👎 ), which would leave out Android and iOS Firefox users.

All desktop users are left in the dark regardless of platform, which I'm OK with.

**Comment by akaplo** [comment]
A note on the Chrome method - it requires us to enable a service worker in the app before Chrome will show the popup.  

The Service Worker script that ships with Ionic is [here](https://github.com/umts/pvta-multiplatform/blob/ionic2/base/src/service-worker.js) and can simply be cleared out to do nothing when run, if we so wish.

This is trivial for us to enable (in Ionic 2), but it seems odd to run a background script for no reason other than so Chrome will show a popup.

**Comment by werebus** [comment]
I think the thinking on service workers is that it's a good indication that this is more than a web page. Otherwise, why am I installing this app?

>  All desktop users are left in the dark regardless of platform, which I'm OK with.

Me too.  There isn't anything for them to install anyway.

**Comment by akaplo** [comment]
True on Chrome's reasoning behind requiring service workers.

So, thoughts on what the service worker should do?  By default, it's implemented as an "aggressive cache."

**Comment by akaplo** [comment]
~Soo #367 would close this.~ False. #367 doesn't include support for showing the app store install banner; just the home screen one.

**Comment by akaplo** [comment]
I think we have this, on [lines 8-12 of manifest.json](https://github.com/umts/pvta-multiplatform/blob/master/src/manifest.json#L8).

**Comment by akaplo** [comment]
Ah yes, closed by #370.
