### ISSUE TITLE
Clicking on a bus in the map shouldn't also click on the route trace

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#306]
^^^^^^^

**Comment by werebus** [comment]
In fact, there doesn't appear to be any utility in having a click/tap event on the route trace at all.

**Comment by akaplo** [comment]
Agreed.  Turns out there's a [property on KMLLayer](https://developers.google.com/maps/documentation/javascript/kmllayer#kml_layer_options): `suppressInfoWindows`.  Seems like it might just serve our purpose.

**Comment by akaplo** [comment]
Yeah, I'm still unsure how to fix this 😞

**Comment by akaplo** [comment]
I think this was actually finally closed via #353.  Not sure what changed, but my original idea from above worked.
