### ISSUE TITLE
RouteStops List Appears Incomplete Due to 40-Stop Display Limit

### ISSUE THREAD

**Issue by sherson** [umts/pvta-multiplatform#309]
Noticed that the stops list for [Route 45](https://m.pvta.com/#/app/routes/20045) is missing [Gulf in/out (231/232)](https://bustracker.pvta.com/InfoPoint/rest/Stops/GetAllStopsForRoutes?routeIDs=20045), though they come up via the search.

**Comment by werebus** [comment]
Isn't that by design? It looks like the list [shows you the closest 40 stops](https://github.com/umts/pvta-multiplatform/blob/222f1381fde6fb490478991034797a46b0a0cfc3/www/pages/route/stop-modal.html#L8). When I look at that list from the office, I also don't see Belchertown Center, e.g.

**Comment by akaplo** [comment]
To clear up at least some of the confusion, I suggest adding the same bar that appears on `Routes and Stops` to the stop list on the Route page:

![image](https://cloud.githubusercontent.com/assets/7144148/22752830/f1923d4c-ee07-11e6-881a-e73ea8cc12e8.png)

**Comment by sherson** [comment]
That'd work. Alternatively, is there a reason not to show more stops? Route 45 has the most at 64 (not counting two that are being removed soon). There are a couple other routes with 40something stops. 

_Edit: That's looking at UMTS routes... I'm not sure if any VATCo/SATCo routes have more stops._

BTW, I thought it was supposed to sort the stops by proximity, but that didn't appear to be the case... I realized later that was simply because the stop list was cached. 

Also confusing me was that a couple of the stops on the list aren't actually on Route 45 or its opportunity trips (that was figured out, and will be fixed the next time we do a Hastus export and Avail publish).

I suppose it's also worth mentioning that the search results originally didn't show the stops not on the list, but reloading the page fixed that. Not sure what happened there.

**Comment by akaplo** [comment]
I believe my original intention for the RouteStops list was to show them all, but there were some VATCo routes with over 100 stops.

**Comment by akaplo** [comment]
OK, so I'm considering wrapping a few things into this issue:

~~- [ ] Sort RouteStops on the fly, similar to how it works on Routes&Stops.~~
- [ ] Add the "too many stops to show" bar to RouteStops

Regarding the sorting, RouteStops are displayed in the order that they come from Avail - the "SortOrder", as Avail calls it.  On the 30, for example, the order is Puffton1, Puffton2, N. Village, Fairfield St, GRC, etc.  @sherson, you'd rather it be by location?

**Comment by sherson** [comment]
I think the order is fine the way it is.

Coincidentally, at the garage the first couple screens of 45 stops looked (at a quick glance) like they're the closest, so I thought that's what it was doing (upon closer inspection, I see several exceptions).

**Comment by akaplo** [comment]
Ok! I'll add the bar to the page, and I think that'll resolve this.  I've updated the title.
