### ISSUE TITLE
Screen readers

### ISSUE THREAD

**Issue by petermarathas** [umts/pvta-multiplatform#313]
- [x]  "PV-Track"

- [x]  Stops on the Route page

- [x]  Routes and Stops - the favorite button for each route/stop hides the ng-click option to redirect to that route/stop.

- [x] Ionicons on About page

**Comment by petermarathas** [comment]
@akaplo

**Comment by akaplo** [comment]
@petermarathas which of these would you like help on? (also I edited your original thing to make it be checkboxes cause I like checkboxes)

**Comment by petermarathas** [comment]
@akaplo 

>  Routes and Stops - the favorite button for each route/stop hides the ng-click option to redirect to that route/stop.

If we could somehow separate the heart from the <code>ng-click</code>, that problem would be fixed. The rest will be easy.

**Comment by akaplo** [comment]
I'll take that on for ya.

**Comment by akaplo** [comment]
> Routes and Stops - the favorite button for each route/stop hides the ng-click option to redirect to that route/stop.

Completed on the [Aria branch](https://github.com/umts/pvta-multiplatform/tree/aria).

**Comment by akaplo** [comment]
Closed via #317.
