### ISSUE TITLE
Route map location not needed

### ISSUE THREAD

**Issue by sherson** [umts/pvta-multiplatform#315]
@akaplo mentioned that route [maps](https://m.pvta.com/#/app/map/route/20030) jumping to the user's location is annoying here. I agree... it's useful for [schedule](https://m.pvta.com/#/app/plan-trip), but isn't needed on the route maps.

**Comment by akaplo** [comment]
Done, removed one line of code.

**Comment by akaplo** [comment]
Closed via #319.
