### ISSUE TITLE
Google Maps API 'Plan trip'

### ISSUE THREAD

**Issue by petermarathas** [umts/pvta-multiplatform#32]
Inputting two addresses, we should figure out a way to use Google Maps API to calculate the routes/stops/times to get from point A to point B. The Avail mobile app does this by redirecting to google, we should figure out a way to implement this without leaving the app.

**Comment by werebus** [comment]
Google definitely has a directions (including transit directions) API.

https://developers.google.com/maps/documentation/directions/

Note that that API _is_ rate- and request-limited.

https://developers.google.com/maps/documentation/directions/usage-limits

**Comment by akaplo** [comment]
Closed via #110.
