### ISSUE TITLE
"Best Screenreader Environment" Readout

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#322]
Was suggested that the first thing the screenreader says is a blurb about the best environment to use the app with screenreaders (which is Chrome with NVDA, btw).  This can be done by including an aria-label (or anything that a screenreader reads that a sighted user doesn't see) at the very beginning of the app.

**Comment by petermarathas** [comment]
I think if the user is on Mac, the best browser is Safari. That's coming from my experience with it. Maybe "Google Chrome, or Safari for Mac users".

**Comment by akaplo** [comment]
Yeah that's fine by me.  I develop exclusively in Chrome and haven't had issues, so it's nice to know we have 2 fully functional browsers 🎉

**Comment by akaplo** [comment]
Closed via #343.
