### ISSUE TITLE
Plan Trip/Schedule Screenreader Issues

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#326]
- [x] Comboboxes need labels.  Screenreader users have no clue what's happening here unless we label them.

- [ ] The "here's a bunch of autocompletions for what you typed" dropdown isn't read out.  Users **must** select one of these suggestions in order for Plan Trip to work (see #327 before fixing this).

- [x] Can't click "search schedule" with standard "click button" keyboard combo - needed a `tab` as well.  Why? Good question.

**Comment by akaplo** [comment]
Item 1 - Half implemented in V1, finished in V2.
At least on VoiceOver, there is a label and it sounds quite definitive to me (screenshot below is for the destination combobox on V2, but is the same for origin in V1 and V2):
![image](https://cloud.githubusercontent.com/assets/7144148/24638755/24c01654-18b9-11e7-84a0-4265f366bcbd.png)

Item 2 - There's not much we can do here as far as I'm aware.  We say "this is a combobox and you have to select something from it."  I think that'll have to do.

Item 3 - not an issue in V2.

**Comment by akaplo** [comment]
@petermarathas and @sherson, given my comment above, are there any outstanding objections to this issue being closed?

**Comment by sherson** [comment]
Is it worth asking Joshua for suggestions about the second item?

**Comment by akaplo** [comment]
It's worth asking him to try the site at `m.pvta.com/beta` in general.

**Comment by sherson** [comment]
^ Emailed him about it.

**Comment by petermarathas** [comment]
Item 2 happens because we can't change the aria settings for Google's autocomplete service. We need to use their autocomplete in order to use their directions, so I think the best option is to just read out "Start typing and then check below" like we have.

Checked out v2 - items 1 and 2 look good -- I think this issue can be closed.

**Comment by sherson** [comment]
Yep, Josh's reply was quite positive. @akaplo is going to look into a different suggestion that Josh made, but we can close this.
