### ISSUE TITLE
Cease Needing Autocomplete Selection on Plan Trip

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#327]
Loosely tied to #326 item no. 2.

On Plan Trip, we require the user to select one of the options that comes up in the Google-supplied autocomplete dropdown before we let them plan a trip.  I'd like this to no longer be a thing, as it's a huge pain in the booty (and it is almost impossible to use with screenreaders).

**Comment by petermarathas** [comment]
This is the only way we can use the Google Directions service, as Google requires us to select the specific Google ID for a location. Maybe we can auto-select the top choice returned by Google whenever the user types anything.

**Comment by akaplo** [comment]
You're correct.  Your suggestion is a good idea, but I've mostly eliminated any erratic behavior from this in v2, so I'll close this issue.
