### ISSUE TITLE
Search Returns Multiple Results For Some Stops

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#33]
I've noticed that when using Search (not Stops) for some stops, it will show multiple duplicate results that all redirect to the same page.

Interestingly, it seems as though this occurs only for stops that are serviced by multiple PVTA contractors.

For example: Arnold House, GRC, ILC, SAB, Mullins Center, Old Belchertown Road, Sugarloaf Estates, and Gatehouse Road all appear <b>only once</b>, and these are all only serviced by UMTS buses.

Haigis, Fearing, Amherst Post Office, Cowles Lane, Stone Shelter, and Amherst Common all appear **3 times**.  They are serviced by **UMTS, VaTCo AND SaTCo**.

University Drive, Amherst Community Health Center, and Southwest Shelter all appear **2 times**.  They are serviced by **UMTS and VaTCo**.

So I'd guess the number of times a stop is reported is directly related to the number of PVTA contractors that service it.  Why? No clue yet.

**Comment by dfaulken** [comment]
Something to do with each garage maintaining a separate Hastus database - @werebus probably knows this one.

Anyway, it's probably find to uniquify stops by name, right, if they're all redirecting to the same place?

**Comment by akaplo** [comment]
In reference to uniquifying, I agree.  It's simply repeating the same object 2 or 3 times.

**Comment by akaplo** [comment]
Also, I'm not sure if this is actually a **bug**, per se, because it is the intended behavior for somebody...just not us.
