### ISSUE TITLE
Is the map on Plan Trip useful?

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#334]
I personally don't find it helpful and am in favor of removing it, but I'm interested in thoughts. @sherson @petermarathas @werebus.

**Comment by petermarathas** [comment]
My thoughts are to keep it, but I put it there initially.

**Comment by sherson** [comment]
I think we should keep the map. Viva la spatial thinking.

**Comment by werebus** [comment]
Keep it. Without the map, you're told to "Walk to *stop name*", which you might not know the location of.

Admittedly, you can find it by tapping on the stop name in the directions and then tapping the map icon, but why add two more stops?

I **do** think that the map could start a little more zoomed in. What matters to me, mostly, is the relative positions of myself and the start of my journey, not the entire journey.

**Comment by sherson** [comment]
That's a good point about the zoom level, though I think it's also acceptable to start with an overview map, and to zoom in on any walking portion(s).

**Comment by akaplo** [comment]
Will keep the map.
