### ISSUE TITLE
Route KMLs

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#36]
As a sort of offshoot of #32, it would be extremely simple for us to include KML overlays onto our maps.  A KML file provides a trace of a specific route.  

So, for example, if you're looking at 3401 on a map and it's currently on the 31, the marker for the bus would be placed as normal, but a pink-ish (the 31's color) trace would be overlaid along the route.

With the Maps Javascript API, it would be as easy as:

``` Javascript
var kmlLayer = new google.maps.KmlLayer({
    url: 'url_to_the_pvta_kml_for_the_route_in_question',
    map: $scope.map
});
```

**Comment by werebus** [comment]
Route KMLs can be found here

http://pvta.com/KML/KMLs.zip

Although that may not be a permanent location, per se.  These might be small enough that including them withing the application wouldn't be that big a deal (except for updates, I guess).
