### ISSUE TITLE
Web Browser Niceties

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#360]
Dur.  Favicon, fix manifest.json, home screen icons for mobile browsers, etc.  `master` has all of this, so it can likely just be copied.

**Comment by werebus** [comment]
Along the same line, [`manifest.json`](https://github.com/umts/pvta-multiplatform/blob/ionic2/base/src/manifest.json)?

**Comment by akaplo** [comment]
Yeah. Renamed issue and updated first comment.

**Comment by akaplo** [comment]
This is all set and ready for a PR, with the exception of the Service Worker.

**Comment by akaplo** [comment]
@werebus and I decided that service worker shall exist and do nothing! 🎈

**Comment by akaplo** [comment]
Closed via #360.
