### ISSUE TITLE
Saved Trips Sometimes Not Loading Correctly

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#380]
Loading a saved trip should work as follows:
![merp](https://cloud.githubusercontent.com/assets/7144148/25925822/15b4d61e-35b9-11e7-9b71-88f15538aa57.gif)

As you can see, everything got populated and the app downloaded the best route and displayed it for you all on its own.

When Plan Trip is the first page to use Maps, we see the following behavior:
![merp](https://cloud.githubusercontent.com/assets/7144148/25925852/5a49413e-35b9-11e7-9809-1ddb40e1c8c4.gif)

Simply, nothing happens.  I suspect that [this line](https://github.com/umts/pvta-multiplatform/blob/master/src/pages/plan-trip/plan-trip.component.ts#L201) of code is the culprit; we're never passing `loaded trip` to Google Maps when we need to get maps **before** doing anything else.

This issue will begin to associate you with the sometimes-unwieldy Plan Trip code, how we use Google Maps, and Ionic's lifecycle events.

**Comment by akaplo** [comment]
I realize now that the problem was in fact created by my own mediocre code that I'm still unsure how to fix.

The [MapService function ](https://github.com/umts/pvta-multiplatform/blob/master/src/providers/map.service.ts#L14) that downloads Google Maps gets passed the correct Plan Trip function as a callback, but the issue is that it **doesn't** [get passed the loadedTrip param](https://github.com/umts/pvta-multiplatform/pull/403/files#diff-8f802a9b80a60c0a01b7ed67374a46b8R201).  Additionally, I don't think you can just pass parameters to the Google Maps callback that the MapService creates.

@mboneil10 provided a good workaround in #403 but this should remain open. 

Perhaps a class-wide `loadedTrip` variable would be a better bet instead of trying to pass it around as a function parameter.  We must've been using one at some point, because [I spot an artifact](https://github.com/umts/pvta-multiplatform/blob/master/src/pages/plan-trip/plan-trip.component.ts#L26).

**Comment by akaplo** [comment]
This is resolved for rlz in #413 - somehow the fact that we **can** pass params to this callback function just like any other escaped my small mind. See the one-liner fix [here](https://github.com/umts/pvta-multiplatform/pull/413/commits/ccb1e3320d7a4c4d53d854a4bc8d393ffa58abd8#diff-8f802a9b80a60c0a01b7ed67374a46b8R200).

**Comment by mboneil10** [comment]
Closed with #413
