### ISSUE TITLE
Pressing Back doesn't close modals

### ISSUE THREAD

**Issue by dfaulken** [umts/pvta-multiplatform#389]
If downloading departures takes forever and I press Back to abort and do something else, the modal remains in place, and the previous page is navigated to underneath it. The only fix seems to be closing and restarting the app.

I would expect pressing back to close the modal, either with or without also going back to the previous page (I think either is fine).

**Comment by akaplo** [comment]
This is a longstanding issue. I'll take a look into this, but it could get hairy.

**Comment by akaplo** [comment]
A newer version of Ionic has baked-in support, but it'd require us to completely rewrite our routing.  See #406

**Comment by mboneil10** [comment]
Is this a sign to upgrade then? 😨 @akaplo

**Comment by akaplo** [comment]
Assuming #413 gets merged, the `enableBackdropDismiss` property on the [LoadingController](http://ionicframework.com/docs/api/components/loading/LoadingController/) should resolve this issue.

> I would expect pressing back to close the modal, either with or without also going back to the previous page (I think either is fine).

With this implementation, tapping anywhere else on the app should remove the loader, freeing you to press ⬅️  to your ❤️ 's content!

**Comment by mboneil10** [comment]
#413 _did_ get merged! I'll work on this. (edit: I realize now that I self-assigned this 19 days ago. LOL)

**Comment by mboneil10** [comment]
And we don't want the property on each of the different modals because that would be too much, correct? Or is that because we don't care if it's a modal -- we want a user to be able to press back on anything that's loading? @akaplo

**Comment by mboneil10** [comment]
Jeez. Past Molly can't read. You answered my question above, @akaplo. Will figure this out.
