### ISSUE TITLE
Map that shows every bus

### ISSUE THREAD

**Issue by bgregg** [umts/pvta-multiplatform#39]
Right now, you can only look at a map with one bus at a time. It would be cool if you could look at a map with all the buses near you (perhaps add a link to it in the index)

**Comment by akaplo** [comment]
I believe @bgregg has begun work on this; assigning him to it so nobody else (aka me) forgets and starts working on it :stuck_out_tongue:

**Comment by akaplo** [comment]
Changing the milestone to beta 4.

**Comment by bgregg** [comment]
This is something I just havent gotten around to. Once we deploy Beta 3, I will work on this first thing.

**Comment by akaplo** [comment]
@bgregg since you're assigned to like 9 issues, I'm gonna start on this one; just let me know that you haven't already.

**Comment by bgregg** [comment]
I have not, just assigned you. If you need assistance let me know, maps is kinda my thing

**Comment by akaplo** [comment]
@werebus has some thoughts on this actually

**Comment by werebus** [comment]
Right, I was having some trouble putting my finger on what he use case was.  That is, how does this feature help me catch a bus?  The only thing I could think of is that it's for the person who thanks they know better that the departure estimates how much time it takes for a bus to get places.

There is the idle curiosity factor: "Look at all those buses! Isn't that cool?" :bus: :bus: :train: 

In addition, there's the wrinkle that about half of the buses "nearby" are not headed towards you.

I think a use-case is warranted before this is implemented.

**Comment by akaplo** [comment]
Interested to hear @petermarathas's thoughts.

**Comment by akaplo** [comment]
Should I close this? @bgregg @werebus

**Comment by werebus** [comment]
I vote:  "yes, close it".
