### ISSUE TITLE
Improve Deletion of Saved Trips, Stops, and Routes

### ISSUE THREAD

**Issue by mboneil10** [umts/pvta-multiplatform#402]
There's no clear way to delete saved trips. Let's make one.

**Comment by werebus** [comment]
:+1: While we're at it, there should maybe be a less weird way to un-favorite routes and stops too.  Right now you have to do that from the given route or stop page. Or, perversly, by clicking on the "Add Routes" or "Add Stops" button.

**Comment by mboneil10** [comment]
The functionality is already there. "Trips can be deleted by using slide to delete on My Buses, like below."
![screenshot_20170703-232052](https://user-images.githubusercontent.com/19267771/27833277-0a46c2bc-60a0-11e7-829e-6e2d7df9d922.png)
Photo and quote from @akaplo.

All that needs to be done is to make the functionality more obvious (@dfaulken).

**Comment by mboneil10** [comment]
Sorry, accidentally closed the issue.

**Comment by mboneil10** [comment]
@werebus, what you're asking for is addressed in #379. @AkivaGreen is working on that in #385.

**Comment by dfaulken** [comment]
We could change the text to "Add / Remove Stops" etc.

Not saying we should. Just that we could.

**Comment by mboneil10** [comment]
I agree, that seems fine to me. I was thinking that under the different headings, e.g. "Your Stops", there could be the text "Swipe right on a favorited stop to delete".

**Comment by mboneil10** [comment]
Is it poor practice to investigate what other apps look like? On other apps, the swipe to delete is not clearly marked on a list of things, but there is an "edit" button in the upper right hand corner. One can delete multiple items at a time in edit mode. Something to consider. I might be getting ahead of myself.

**Comment by akaplo** [comment]
Like @mboneil10 mentioned, the list headers could include an "edit" button that would reveal delete buttons on all the list items when clicked.  This was an old design principle on iOS that I recall liking - not sure if they still use it.

**Comment by werebus** [comment]
I don't mind the swipe-to-delete interface , but I have a minor concern.  I forgot that it was a thing, and wasn't able to discover it again. There should be some sort of indicator, but I don't know what.

Looking over the [Material Designs specs][1], our list looks a lot like the example of a "leave-behind". But...not exactly. The separator on our list doesn't extend all the way to the edge - in the MD examples, the list items look more like individual entities, which *maybe* subtly communicates that they can be manipulated.

I also agree that the "Add Routes" and "Add Stops" buttons can be a "Edit" buttons, perhaps an `ion-edit` icon?

[1]:  https://material.io/guidelines/components/lists-controls.html#lists-controls-types-of-list-controls

**Comment by artarazavi** [comment]
I noticed a lot of apps also use the long-press function when you press and hold an item and check-boxes appear then you can delete multiple items at a time. But they use that functionality along with the edit button. Just a suggestion :)
