### ISSUE TITLE
Ionic 3

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#406]
**EDIT 8/3/17** Either I was misunderstanding from the beginning or they fixed this in some updates to 3.x, but most of what I believed was barring us from upgrading was simply untrue.  See #413.

**ORIGINAL**
Ionic 3 has been stable for almost 2 months.  There's a single major roadblock for us to update to it: routing.  We use explicit URLs (/favorites, /settings, etc) like a website, which Ionic has decided to make significantly harder.

In order to use this kind of routing, we must use their [IonicPage](http://ionicframework.com/docs/api/navigation/IonicPage/) and "Lazy Loading" features, which require a separate module for each page (instead of just an `app.module.ts`, we'd need to add a `page_name.module.ts` for each page in the app), which in my opinion is a ridiculous design choice that creates a lot of unnecessary code replication.

See [part 1](http://blog.ionic.io/ionic-and-lazy-loading-pt-1/) and [part 2](http://blog.ionic.io/ionic-and-lazy-loading-pt-2/) of a 2-part official post on the topic.

So, what I'm interested in determining is: should we just stick with Ionic 2.x?  Bite the bullet, take the duplication hit and keep moving with Ionic?  Or, change how we think about our routing?

**Comment by mboneil10** [comment]
Whoa. I'm completely split on this. The change would create a lot of unnecessary duplicate code. Seeing as how frustrated I get with the [four main pages all containing the same navmenu](https://github.com/umts/pvta-multiplatform/blob/9649ea1c72f5db51337062bbd55e4ba26dfd4387/src/pages/settings/settings.html#L2), I don't know how we could deal with fixes if everything is completely spread out. In terms of keeping our code clear, I vote no on upgrading. But in general, it always seems like a good idea to upgrade our apps.

**Comment by mboneil10** [comment]
Since you said Ionic 3 would help us out with [this bug](https://github.com/umts/pvta-multiplatform/issues/389), I'm currently torn. Will label pros and cons to updating. We'll figure something out.

**Comment by akaplo** [comment]
Yeah, same.  Input from others like @Anbranin, @werebus, and @dfaulken might help!

**Comment by mboneil10** [comment]
plz

**Comment by mboneil10** [comment]
Let's just try it out.

**Comment by akaplo-cb** [comment]
I think I did most of this work at one point - if somebody decides to hack at this, please wait till I get home tonight and see if I have a local branch sitting on my computer.

**Comment by akaplo** [comment]
I think I did most of this work at one point - if somebody decides to hack at this, please wait till I get home tonight and see if I have a local branch sitting on my computer.

**Comment by mboneil10** [comment]
Ok, I won't. I'll be working on the delete favorite routes and stops thing. I don't see anyone picking it up today. Thanks Aaron! 👍

**Comment by mboneil10** [comment]
@Anbranin said yes, too. I'll do this later. If you still didn't find it.

**Comment by akaplo** [comment]
Yeah. Sadly, that branch must've gotten deleted out of either carelessness or frustration (both of which would be my fault).

**Comment by mboneil10** [comment]
Ok. I try today.

**Comment by akaplo** [comment]
I'll drop assorted oddities from the upgrade in this comment

1. ![image](https://user-images.githubusercontent.com/7144148/28755077-aaeef43e-7520-11e7-9b21-f308c830e375.png)

**Comment by mboneil10** [comment]
We're at a point where we get something similar to [this issue](https://github.com/umts/pvta-multiplatform/issues/371), and the `console.error` reads: `PlanTripComponent ionViewWillEnter error: google is not defined`. Problem with loading.

**Comment by akaplo** [comment]
PR is good to go.  Issue described by @mboneil10 was solved by using anonymous callbacks properly and is **also present on master**.
