### ISSUE TITLE
Too Much Toast?

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#409]
[This commit](https://github.com/umts/pvta-multiplatform/commit/6185b0ebb32818a7fab568121aabdbd613e475cd) added toasts on the Routes & Stops page when you favorite or unfavorite a route, but they don't hide themselves.  You could end up with an annoying number of them, like so:

![toast](https://user-images.githubusercontent.com/7144148/28502673-4a7860b4-6fc5-11e7-95cc-90f0b4a59a0a.gif)

Is this worth fixing?

**Comment by mboneil10** [comment]
I find the amount of toasts to be saddening, too. Do you mean setting a duration for the favorite toast messages? We could add a duration to [this line](https://github.com/umts/pvta-multiplatform/blob/master/src/providers/toast.service.ts#L11). If you mean hiding it, then that could be done with some sort of if statement in the toast service. Either way, I think this could be a quick fix but not top priority.

**Comment by akaplo** [comment]
Yup!  Duration is a solution, or we could make the Toast service close an open Toast whenever it tries to make a new one.

**Comment by mboneil10** [comment]
Granted, it's not like anyone is favoriting routes and stops wildly. But I could do this.

**Comment by mboneil10** [comment]
![less-toast](https://user-images.githubusercontent.com/19267771/28755088-db58a0e8-7520-11e7-8288-888103456c62.gif)
