### ISSUE TITLE
"Edit Favorite Routes": Items should be tappable

### ISSUE THREAD

**Issue by janpio** [umts/pvta-multiplatform#417]
The list items on "Edit Favorite Routes" should be tappable to select the checkbox on the left. (similar to "Edit Favorite Stops")

**Comment by janpio** [comment]
Ha, this seems to be possible if you don't tap the text but on the empty space. Something seems to catch the event on the text...

**Comment by mboneil10** [comment]
Oh, good catch @janpio!

**Comment by mboneil10** [comment]
It also appears that they are only tappable at the edges of the item box.

**Comment by mboneil10** [comment]
Ah! The issue is with the columns.
