### ISSUE TITLE
Routes List should show UMTS buses first

### ISSUE THREAD

**Issue by bgregg** [umts/pvta-multiplatform#42]
Right now, it shows all of the UMTS buses at the bottom because it sorts routes alphabetically with numbers last. Definitely should should show our buses first.

**Comment by werebus** [comment]
Well, the routes should be in an order that allows PVTA riders to find what they're looking for easier.  UMTS has had this conflict with the rest of PVTA for a while: do routes have a leading letter or not?
-  Our old mobile schedules page put numerals first
-  Avail puts letters first
-  The PVTA website ignores the letter and puts them in numeric order.

Of those, the 3rd is probably the easiest for users, but the least "logical" from our standpoint.
