### ISSUE TITLE
Nice app!

### ISSUE THREAD

**Issue by janpio** [umts/pvta-multiplatform#421]
Hey, just noticed your app via a comment on some Ionic issue, and played around a bit what also caused me to create some issues for stuff that might be improved. But I didn't only want to leave "negative" feedback, so this additional issue to tell you that I really like the app and wish something as simple and nice would exist for Berlin. Keep up the good work!

**Comment by akaplo** [comment]
Thanks @janpio!  We really appreciate the feedback (both types 😉 ).  We're a student-run University bus garage, so the thought of people abroad being somewhat jealous of our system is awe-inspiring!
