### ISSUE TITLE
Master is Broken

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#426]
This is what's currently on [master](https://github.com/umts/pvta-multiplatform/commit/144edcf509d09fc8cd05aa94b0063240737257e1):

![image](https://user-images.githubusercontent.com/7144148/29852786-06c2f610-8d0a-11e7-8a02-54d801d575f7.png)

Narrowed it down us having two conflicting versions of localforage - one that Ionic uses, and one in our [package.json](https://github.com/umts/pvta-multiplatform/blob/144edcf509d09fc8cd05aa94b0063240737257e1/package.json#L44).  

Removing ours should fix the problem.

**Comment by mboneil10** [comment]
Oh no
