### ISSUE TITLE
Re-Enable momentjs Suffixes

### ISSUE THREAD

**Issue by dfaulken** [umts/pvta-multiplatform#431]
Looking at the screen which lists multiple upcoming departures of a particular route at a stop, I saw this:

Real time | "Scheduled" | "Estimated"
--- | --- | ---
8:24 am | 8:24 am | 8:28 am (4 minutes)
8:28 am | 8:24 am (4 minutes) | 8:28 am

Since I didn't look at my phone during the intervening 4 minutes, it caught me off guard a little. Perhaps we should distinguish between "in 4 minutes" and "4 minutes ago"?

**Comment by akaplo** [comment]
Great catch @dfaulken. Easily reproducible.

Solution: http://momentjs.com/docs/#/displaying/fromnow/

> If you pass true, you can get the value without the suffix.

> moment([2007, 0, 29]).fromNow();     // 4 years ago
> moment([2007, 0, 29]).fromNow(true); // 4 years

[One liner fix for us](https://github.com/umts/pvta-multiplatform/blob/master/src/pages/stop/stop.component.ts#L187).
