### ISSUE TITLE
Some screens do not have enough padding for the nav bar

### ISSUE THREAD

**Issue by arbass22** [umts/pvta-multiplatform#432]
Screenshot taken on iPhone 7, iOS 10.3.3

![bus](https://user-images.githubusercontent.com/10891729/30407279-618a0c98-98c5-11e7-9c4a-f1a7c21e8607.png)

**Comment by akaplo** [comment]
Thanks @arbass22!  We know about this and can reproduce it sporadically, but I'll look more seriously into it very soon.

**Comment by mboneil10** [comment]
I'm not sure how to reproduce this issue, but I've been looking up solutions to the problem. How can I recreate it?

**Comment by mboneil10** [comment]
So, this seems like this could be a combination of our app, [an ionic issue](https://github.com/ionic-team/ionic/issues/13294), and just iOS in general. Will come back to this soon.
