### ISSUE TITLE
Preserve stop-sort preference

### ISSUE THREAD

**Issue by werebus** [umts/pvta-multiplatform#436]
We got this report via email:

>  When one goes to a saved stop and reorders the list of routes by 'time' rather than the default 'route', this change is not saved, and the setting will always be reset to 'route' when returning to the saved stop, even within the same session.

And that's true. It's not a saved setting, but rather a temporary view change. Should we save it somehow?

It sounds like this person expected the choice to be preserved _per stop_. Or at lease per favorited stop.

**Comment by akaplo** [comment]
To be fair, it _did_ persist in 1.x, this user could've come from there and wondered why that functionality was lost.  I'll check the analytics and report how often it was used - anyone have any arguments for or against?

**Comment by werebus** [comment]
We got another request via email:

>  Is there a way to set stops to always default display by time, rather than route? Display by time is far more useful to me but I don't like having to always redisplay the stop by time each time I visit the stop. I want to set this preference app-wide so all stops always default to display by time.

Although they are looking for an app-wide setting.

**Comment by akaplo** [comment]
Welp, the 1.x style solution should still work.  I've made it high priority, since we've had 2 (❗️ 👻 ) users request it.  If you wish to respond, just say the app will remember their choice automagically in the next release.

**Comment by jrgriff** [comment]
Hi, I am the second reporter. Remembering the preference on a per-stop basis ("1.x style") should be acceptable for my use, although an app-wide setting would certainly be preferable, as I will never want to use the order-by-route view (this view has honestly never made sense to me – but that’s a matter of personal preference I suppose…).

**Comment by dfaulken** [comment]
I'm working on an app-wide setting.
