### ISSUE TITLE
Add FAQ

### ISSUE THREAD

**Issue by sherson** [umts/pvta-multiplatform#442]
PVTA has expressed interest in adding text about inclement weather. They cited these as examples:
* http://metro.nfta.com/pdfs/Winters%20Rider%20Guide-web.pdf
* http://www.ci.oshkosh.wi.us/transit/assets/pdf/Winter_Weather_Tips.pdf

Perhaps we should consider a FAQ? Can have topics related to using the app, but I'm thinking it'd primarily be about riding buses. For reference:
* https://www.umass.edu/transportation/faqs

<sub><sup>(A lot of what's in the GoTransit and NFTA PDFs should be common sense, and I'm reluctant to add that much text to our app, but perhaps we could incorporate some of it)</sub></sup>

**Comment by mboneil10** [comment]
This doesn't sound like a bad idea to me, even if it adds a lot of text to our app.

**Comment by sherson** [comment]
OK, [Seritta](http://umass.edu/transportation/seritta-norige) will be adding some more winter tips to http://umass.edu/transportation/faqs in the next couple weeks. We'll coordinate with her.

**Comment by mboneil10** [comment]
@sherson any news on this?

**Comment by sherson** [comment]
Seritta didn't add it to the website FAQ, but she created this news item http://www.umass.edu/transportation/winter-rider-guide-and-tips. When I have some time, I'll try to come up with some text for the app FAQ about winter and other topics (or if someone else wants to do that, feel free).

**Comment by sherson** [comment]
Seritta is going to put together some text for us.

**Comment by akaplo** [comment]
Could also have a link somewhere in the app (perhaps in Settings?) that'll show users that webpage in-app (without taking them away from us and to their browser). Would make our lives easier and provide the same value.
