### ISSUE TITLE
Display public messages on stop page

### ISSUE THREAD

**Issue by sherson** [umts/pvta-multiplatform#447]
Someone might not realize that [a detour](https://bustracker.pvta.com/InfoPoint/rest/PublicMessages/GetAllMessages) affects the stop they're viewing.

BusInfoBoard implementation, for reference: umts/BusInfoBoard#72

**Comment by werebus** [comment]
This should be all messages for all routes that service that stop?

[Oh if only...](https://developers.google.com/transit/gtfs-realtime/reference/#enum_schedulerelationship)
