### ISSUE TITLE
Underscore.js

### ISSUE THREAD

**Issue by dfaulken** [umts/pvta-multiplatform#45]
For dealing with collections of data, [Underscore.js](http://underscorejs.org/) has lots of great methods for sorting, iterating, etc.

How do you feel about incorporating it?

**Comment by dfaulken** [comment]
Here's an example [from the routes controller](https://github.com/umts/pvta-multiplatform/blob/master/www/js/controllers/routes-controller.js#L6-L12):

In this code, we're trying to store a collection of objects, but for each object, store just a few of their properties:

``` js
for(var route = 0; route < $scope.routes.length; route++){
  $scope.routes[route] = {
    LongName: $scope.routes[route].LongName,
    ShortName: $scope.routes[route].ShortName,
    RouteId: $scope.routes[route].RouteId,
    Color: $scope.routes[route].Color,
  }
}
```

With Underscore, this [is](http://underscorejs.org/#map) one [line](http://underscorejs.org/#pick):

``` js
$scope.routes = _.map($scope.routes, route, _.pick(route, 'LongName', 'ShortName', 'RouteId', 'Color'));
```

**Comment by akaplo** [comment]
I think that's a fantastic idea!  Definitely a worthy addition.
