### ISSUE TITLE
Package.json fixes

### ISSUE THREAD

**Issue by mboneil10** [umts/pvta-multiplatform#480]
Remove [this line](https://github.com/umts/pvta-multiplatform/blob/master/package.json#L49) and the one below. Might cause some trouble? Deemed unnecessary at the least.

**Comment by werebus** [comment]
>  Deemed unnecessary

I _think_ so?

**Comment by werebus** [comment]
So, I can confirm that Cordova now puts them in there (when you manipulate them with `ionic cordova platform <whatever>`). Likewise with plugins.

They should stay in.
