### ISSUE TITLE
Filter active alerts

### ISSUE THREAD

**Issue by dfaulken** [umts/pvta-multiplatform#50]
From #48, it would be nice if we filtered active alerts with the same logic that decides whether they're shown on the PVTA main page, etc.

Some attributes we could look at to do this:
- applicable weekdays
- start and end datetime
- whether they're published or not

I'm not actually sure what those other pages do.

**Comment by akaplo** [comment]
Which "other pages" do you mean?

**Comment by dfaulken** [comment]
PVTA's website is what springs to mind.

**Comment by akaplo** [comment]
Ohh, you mean what they do to filter the messages.  Got it.

My question: does the endpoint **currentmessages** do this for us?  ie the 34/35 message is set to end on May 7.  Will it disappear from the endpoint at that time?  This example is active every day, but is the same true for messages that aren't active on, say, weekends?  Will they disappear from **currentmessages** during those times?  I don't expect anyone but Avail to know, but worth asking before implementing.

**Comment by akaplo** [comment]
So there still isn't a good answer to the "does the api do this for already" question.  I'm going to look into that.  

## I'll also tack onto this issue by adding the following addition to its scope:

Add to **My Buses** logic to only display alerts that pertain to favorited routes.
