### ISSUE TITLE
Stops List Broken

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#53]
#52 and #37 have combined to break the list of stops on the Stops page.

The issue: #37 changed the iteration technique to `collection-repeat`, which demands an array to iterate over.  This was done because it produces a much faster result for large datasets, which we certainly have.  #52 changed the type of the central stopslist to Object, which collection-repeat won't accept.

Additionally, #52 sorts the stops by Name when passing them to the factory (which undoes the geographic sorting we have Avail doing for us now), so changing [this line](https://github.com/umts/pvta-multiplatform/blob/d7e6a78fdbd36d9a17be21aa95bceb7902e9b739/www/templates/stops.html#L7) to use ng-repeat will fix the runtime exception, but we still have the list sorted improperly.

I've reverted #52, because I'd prefer to not have a broken build sitting in Master.

**My question:** what is the best way to do this?  Keeping [the stops list](https://github.com/umts/pvta-multiplatform/blob/a0d95f135624f510862afde6fcb0b26a674d7705/www/js/services.js#L51) as an object means that the Stops page on phones (it works fine in the browser) makes the app unusable, because ng-repeat can't handle the data.

This problem is solved by using an array and `collection-repeat`, but (@dfaulken) does this mean we can't use Underscore's awesome `uniq` method?  If we can use `uniq` on an array, we could just uniquify by Name but keep the sorting as it was when it was delivered by Avail (by removing [this line](https://github.com/umts/pvta-multiplatform/blob/a0d95f135624f510862afde6fcb0b26a674d7705/www/js/services.js#L54)?).

I'm not sure what the best solution is.

**Comment by dfaulken** [comment]
In #52 it's an object of objects. Seems like an array of objects would be fine too.
