### ISSUE TITLE
Map for embedding in other sites?

### ISSUE THREAD

**Issue by sherson** [umts/pvta-multiplatform#56]
This is a bit of a kludge, but Transit's public website has the MyAvail mobile map embedded as an iframe. For example, [Route 30](http://www.umass.edu/transportation/route-30-north-amherstold-belchertown-road):

<img width="611" alt="screenshot 2016-02-16 14 49 45" src="https://cloud.githubusercontent.com/assets/409008/13088979/93b27e2c-d4bc-11e5-98b6-34081827a5bf.png">

Since the middle of last year, the page loaded with the map already showing the specific trace/stops and buses for that route.

This was done with a slightly modified version of Avail's bookmark (we changed [fullscreen](http://bustracker.pvta.com/InfoPoint?fullscreen=true&map%5Bfilter%5D%5Broutes%5D=true&map%5Bfilter%5D%5Bstops%5D=true&map%5Bfilter%5D%5Bbuses%5D=true&messages%5Bactive%5D=false&messages%5Bfilter%5D=false&routes%5Bselected%5D=20030&routes%5Bsearch%5D=&stops%5Bactive%5D=false&stops%5Bsearch%5D=) to [mobile](http://bustracker.pvta.com/InfoPoint?mobile=true&map%5Bfilter%5D%5Broutes%5D=true&map%5Bfilter%5D%5Bstops%5D=true&map%5Bfilter%5D%5Bbuses%5D=true&messages%5Bactive%5D=false&messages%5Bfilter%5D=false&routes%5Bselected%5D=20030&routes%5Bsearch%5D=&stops%5Bactive%5D=false&stops%5Bsearch%5D=) in the URL parameters. Like I wrote... Kludge).

Recently (likely due to the MyAvail upgrade), that stopped working. The mobile URL now loads without the trace/stops, or buses, and users need to search for the route and click "View Map" . 

I emailed Avail about it. Not sure if/when this will be addressed, and I'm wondering if it makes sense to create a map utilizing pvta-multiplatform that could be embedded instead. Any opinions?

**Comment by akaplo** [comment]
As a matter of fact, this would be extremely simple.

3 minutes of editing has produced this:
<img width="1440" alt="screen shot 2016-02-18 at 11 51 33 am" src="https://cloud.githubusercontent.com/assets/7144148/13150975/fafa923e-d635-11e5-94ad-e291a1cba456.png">

The blue outline (not sure why it's blue yet **edit: it's blue because Avail has the wrong color entered in the kml...the 31's is pink as expected**) is the overlay of the 30's route.

This is running in multiplatform, but it could quite easily be added to the source for Transit's public website.

**Comment by akaplo** [comment]
@sherson, did I (at least partially) answer your question?

**Comment by sherson** [comment]
Yep, thanks! Let's talk more about this today.

Will ask about Route 30's [8-digit hex](https://developers.google.com/kml/documentation/kmlreference#color) at http://pvta.com/KML/KMLs.zip (should be `7f20a0c7`):

``` XML
<name>Route 30 Segments</name>
<description>Route 30 Segments</description>
<Style id="track">
    <LineStyle>
    <color>7ff28f31</color>
    <width>3</width>
    </LineStyle>
</Style>
```

Route 30's color is correct in the Avail [feed](http://bustracker.pvta.com/InfoPoint/rest/Routes/GetAllRoutes):

``` XML
<Route>
<Color>C7A020</Color>
<Directions i:nil="true"/>
<GoogleDescription>North Amherst / Old Belchertown Rd</GoogleDescription>
<Group i:nil="true"/>
<IncludeInGoogle>true</IncludeInGoogle>
<IsHeadway>false</IsHeadway>
<IsVisible>true</IsVisible>
<IvrDescription>North Amherst Old Belchertown Rd</IvrDescription>
<LongName>North Amherst / Old Belchertown Rd</LongName>
<Messages/>
<RouteAbbreviation>30</RouteAbbreviation>
<RouteId>20030</RouteId>
<RouteRecordId>2</RouteRecordId>
<RouteStops i:nil="true"/>
<RouteTraceFilename>route30.kml</RouteTraceFilename>
<RouteTraceHash64 i:nil="true"/>
<ShortName>30</ShortName>
<SortOrder>50</SortOrder>
<Stops i:nil="true"/>
<TextColor>FFFFFF</TextColor>
<Vehicles/>
</Route>
```

**Comment by sherson** [comment]
PVTA had manually changed the color... they're changing it back.

**Comment by akaplo** [comment]
So we can use some of our map code on Transit's public site but it'd require more changes than I'd originally thought (because our ionic / angular code would need to be ported).  

I'm gonna close this issue in favor of opening one in that repository.

**Comment by werebus** [comment]
"that repository"

You're funny.
