### ISSUE TITLE
Code Climate

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#59]
Covers addition of CodeClimate checks in our app.  Not sure how well it knows Angular, but worth looking into.

**Comment by akaplo** [comment]
@dfaulken and @werebus I've made some progress on this (on Master), but I feel like there's a lot more I can add to [.codeclimate.yml](https://github.com/umts/pvta-multiplatform/blob/master/.codeclimate.yml) that would help it to better score us.  Do either of you know of anything?

**Comment by dfaulken** [comment]
Nothing that I know of - their engine docs are pretty good, so if there's nothing else there that strikes your fancy, I'm sure it's fine.

**Comment by akaplo** [comment]
Perfect. Closed.
