### ISSUE TITLE
URL Repetition

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#6]
The app has many <code>$resource</code> calls that retrieve data from Infopoint.  Each one takes, as a parameter, a full URL. In each of these URLs, the portion 

http://bustracker.pvta.com/InfoPoint/rest/ <b>never changes</b>.

As noted by @werebus in #4, we should move the unchanging part into configuration files to eliminate having to type (or copy and paste) this every time.

By making it a variable available throughout the app, we can perform string concatenation when needed to produce full urls that retrieve the data necessary, for example

http://bustracker.pvta.com/InfoPoint/rest/vehicles/getallvehicles.

**Comment by bgregg** [comment]
I'll check it out
