### ISSUE TITLE
Displaying Active Detours

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#65]
Avail's "getcurrentmessages" endpoint provides us with longstanding detours/messages that have been entered by us, but not shorter things like "Route 30 is bypassing Valley Medical due to slippery conditions." I assume Satco  and Vatco  also have methods of communicating detours, but I've never seen any of them in currentmessages (and thus on pvta-multiplatform). 

Is there anywhere where these kind of Detours are stored(other than, say, twitter), and is there a way for us to pull them in?

**Comment by dfaulken** [comment]
So under normal circumstances, `getcurrentmessages` will contain detours like that, and in fact all detours. At the moment there are some issues preventing folks from connecting.

**Comment by akaplo** [comment]
Got it!
