### ISSUE TITLE
Remove Vehicle List From Sidebar

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#7]
No end-user that isn't a Transit/PVTA person is ever going to use the page dedicated to the list of all vehicles on the road. I have it in there because I needed to be sure I knew what I was doing when I started the app.

Since, as of #3, the functionality to find a bus, if you need it, is built into Search, this page can be removed. 

This would involve:
1. Removing <code>vehicles.html</code> entirely
2. Cutting the Vehicle list controller ('VehiclesCtrl') from <b>controllers.js</b>
3. Removing the <code>state</code> titled <b>app.vehicles</b> from <b>app.js</b>
4. Removing the <code>ion-item</code> in <code>menu.html</code> that contains the reference to <code>#/app/vehicles</code>

**Comment by dfaulken** [comment]
I'll take this - removing stuff is probably an easy way for me to start getting oriented.

**Comment by akaplo** [comment]
Great! I don't expect you to have any issues, but let me know if you do.

**Comment by dfaulken** [comment]
Thanks!

**Comment by dfaulken** [comment]
Not going to be able to do this.

**Comment by akaplo** [comment]
No worries!

**Comment by akaplo** [comment]
Accidentally pushed my fix for this to master, but it works.  Closed.
