### ISSUE TITLE
PVTA Meeting

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#70]
This is mainly a question for @sherson, but @dfaulken and @werebus are welcome to contribute.  

As the app nears something that's presentable, how would we go about presenting it to the PVTA brass so that becomes "official?"

Additionally, what would we consider a "ready" state?  It's far from ready, but it gets closer and closer with each PR, so I don't think it's too unreasonable to start thinking ahead.

**Comment by sherson** [comment]
I'm going to call the PVTA Project Manager about a few topics today or Monday. This is one of them.

Depending on what she says, perhaps we can present it at the next PVTA Service Review (I'll double-check with Glenn about when it is).

Do you time to go through it with me this afternoon? (perhaps before code review)

**Comment by akaplo** [comment]
@sherson awesome! Let me know when you hear back.

I messaged you on Slack about a time to go through it (not sure if you check it/get notified)

**Comment by akaplo** [comment]
Closing this.  @sherson let me know when you hear about any updates.

**Comment by sherson** [comment]
Nothing specific to report, but the PVTA project manager and I talked yesterday; we'll setup a time to do a demo (they're straight out right now).

Also, I'm usually on slack (I wasn't getting notifications until now).
