### ISSUE TITLE
Stop Map doesn't show your location

### ISSUE THREAD

**Issue by bgregg** [umts/pvta-multiplatform#74]
For some strange, mystical reason, the map that renders a stop does not show your location. It doesn't make any sense. Definitely worth looking into.

**Comment by akaplo** [comment]
As magically as it appeared, it seems to have been resolved.  See below for me requesting Arnold House be mapped.

<img width="1440" alt="screen shot 2016-03-04 at 7 52 59 pm" src="https://cloud.githubusercontent.com/assets/7144148/13544334/c1015680-e242-11e5-86da-c6a3ffb957b0.png">
