### ISSUE TITLE
Beta Testing

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#75]
As we continue to improve multiplatform and prepare it for launch, I'd like to launch a beta program for UMTS people and others who are interested in testing the app before it's released.

Does anyone know how we'd go about doing this?  I think we could send a notification on round3 and perhaps include a link to download it for Android (for iOS, they'd have to come to one of us).  At the very least, I'd like to have each of us (that ride buses, anyway) trying it out.

I'm interested to hear what people think, this is an **everyone** question.

**Comment by werebus** [comment]
I know the Android marketplace has [a mechanism for beta-testing](https://support.google.com/googleplay/android-developer/answer/3131213?hl=en), though it does require a developer account.

**Comment by sherson** [comment]
I emailed AFS about registering as an Apple developer and as a Google Play developer (regarding legal concerns, paying the fee, and getting in touch with those on campus that are already registered).

You'll know when I know.

**Comment by akaplo** [comment]
As an FYI, the "current" beta release is available for easy downloading and installing on Android [here](https://github.com/umts/pvta-multiplatform/releases/tag/v0.5.2-beta.2)

**Comment by akaplo** [comment]
Closing this until @sherson hears anything further.

**Comment by sherson** [comment]
Nothing specific to report, but the PVTA project manager and I talked yesterday; I asked about registering as developers. 

Will followup with them next week... it may take a bit, but I think it'll happen. In the meantime, we'll continue to test it internally.
