### ISSUE TITLE
Map Failure on Routes With No Buses

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#77]
When mapping a route that currently has no buses on it, the current location and the KML are both properly plotted on the map, but the map centers itself on the middle of the world (which, by default, is the default).

So, there's an issue when we call `bounds.extend` when adding attempting to add vehicle locations to the map that only occurs when there aren't actually any vehicles to add.

Steps to reproduce:
1. Find a route with no buses on it.
2. Go to that route's page.
3. Click the "map this route" button on the bottom of the page.

It'll draw the KML and then send you to the middle of the pacific.  If you zoom out and pan your way back into our service area, you'll see your current location and the route desired have both been successfully plotted.

**Comment by bgregg** [comment]
This (should be) fixed by PR #79.

**Comment by akaplo** [comment]
This has indeed been closed by #79.  Good work!
