### ISSUE TITLE
Add a Stop List Page to the Sidebar

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#8]
Although Search contains the ability to see a list of Stops, they're mixed in amongst Routes and Vehicles.

Adding a page to the sidebar consists of the following:
1. Add <code>stops.html</code> to the <code>templates</code> directory.
2. Create a <b>state</b> called <b>app.stops</b> in <code>app.js</code>
3. Create a controller called <b>StopsCtrl</b> in <code>controllers.js</code>
4. Add an <code>ion-item</code> in <code>menu.html</code> that is essentially identical to all the others but references <code>#/app/stops"</code>

**Comment by akaplo** [comment]
@bgregg, I think that this is a good 2nd project for you.  It, again, can be a lot of copy and paste, but you're likely to run into an error or two when changing stuff around (possibly related to dependencies) that should be helpful in adding to your understanding of Angular's workflow.

**Comment by bgregg** [comment]
Sounds good I'll get working on it!

**Comment by akaplo** [comment]
Great! If you run into issues while I'm not around, hit up Slack (just cause it's easier to respond with code and whatnot than texting, you know?).
