### ISSUE TITLE
Store kml Zip File Locally

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#83]
As opposed to pulling a single KML from Avail every time we wish to plot a route, we should download and save (and redownload at some interval) the zip file that contains all KMLs.

**Comment by akaplo** [comment]
So it looks like it's not physically possible for this to happen.

I wrote code that successfully downloads the KML .zip from PVTA, unzips it, and saves it.  The issue is that Google's API needs a publicly accessible KML file _hosted on the Internet_ to add to the map (see [this StackOverflow article](http://stackoverflow.com/questions/3514785/loading-a-local-kml-file-using-google-maps) for some backup).

I think we assumed that the map would be able to add the KML trace locally, and as such, we could download the entire .zip of them once instead of getting individual KMLs every single time.  **This is not the case**.  The Maps API takes a public accessible URL and downloads it, parses it, and adds it to the map on its end, not ours.  After it has done this, it returns to us a map with the KML overlain.

So, we're going to have to rely on PVTA (and/or Avail) to continually provide updated KML traces for each route.  This one seems to be out of our hands. 

@sherson, @werebus, or @dfaulken, if you have anything to add here, please do. Closing #83.

**Comment by dfaulken** [comment]
I think it might be worth touching base with Google on this one, just to make sure there isn't a way to do this.

**Comment by werebus** [comment]
I do have one thing to add, yes.  Noticed this when Adam posted the link to [PVTA's Swagger docs](http://bustracker.pvta.com/InfoPoint/swagger/ui/index):

```
$ http GET http://bustracker.pvta.com/InfoPoint/rest/TransitAuthorityConfig/Get
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Content-Length: 476
Content-Type: application/json; charset=utf-8
Date: Tue, 15 Mar 2016 18:12:50 GMT
Expires: -1
Pragma: no-cache
Server: Microsoft-IIS/8.5
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
X-UA_Compatible: IE-10

{
    "AnalyticsCode": "UA-0000000",
    "BaseUrl": "http://bustracker.pvta.com/InfoPoint/",
    "BitlyApiKey": "<redacted>",
    "BitlyUsername": "<redacted>",
    "EnableSms": true,
    "EnableSsl": false,
    "EnableTripPlanning": true,
    "ImageUrl": "Resources/Images/",
    "KmlUrl": "Resources/Traces/",
    "NorthEastPoint": "42.595000, 72.230833",
    "SouthWestPoint": "41.930278, 72.929722",
    "SslDomain": "",
    "StartLatitude": "42.233814",
    "StartLongitude": "-72.629445",
    "StartZoom": "10",
    "VehicleRefreshInterval": 10
}
```

```
$ http GET http://bustracker.pvta.com/InfoPoint/rest/Routes/Get/20031
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Content-Length: 1343
Content-Type: application/json; charset=utf-8
Date: Tue, 15 Mar 2016 18:15:23 GMT
Expires: -1
Pragma: no-cache
Server: Microsoft-IIS/8.5
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
X-UA_Compatible: IE-10

{
    "Color": "EF4E91",
    "Directions": null,
    "GoogleDescription": "Sunderland / South Amherst",
    "Group": null,
    "IncludeInGoogle": true,
    "IsHeadway": false,
    "IsVisible": true,
    "IvrDescription": "Sunderland South Amherst",
    "LongName": "Sunderland / South Amherst",
    "Messages": [],
    "RouteAbbreviation": "31",
    "RouteId": 20031,
    "RouteRecordId": 3,
    "RouteStops": null,
    "RouteTraceFilename": "route31.kml",
    "RouteTraceHash64": null,
    "ShortName": "31",
    "SortOrder": 51,
    "Stops": null,
    "TextColor": "FFFFFF",
    "Vehicles": [ ... ] 
}
```

Given that it's a public feed result (and not scraped from the Chrome developer tools), I think it's safe to use `BaseUrl` + `KmlUrl` + `RouteTraceFilename` as the route's KML trace.

**Comment by werebus** [comment]
As far as @dfaulken's [comment](#issuecomment-196956859), There seems to be pretty good consensus on the linked SO article.  It makes sense, in that Google is doing the processing of an XML-ish file into an image on their servers rather than in the "browser".
