### ISSUE TITLE
GTFS Data

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#9]
GTFS (google it) contains CSV schedule data.  This is an offshoot from #2 when it comes to data saving, but is an entirely different issue.

We should include GTFS data in our app because it would enable users to select a day, time, route, and location from (say) a dropdown list. This sounds easier than googling PVTA schedule PDFs and searching through them (I've heard they can be confusing to passengers) and is a good, interactive way to plan your trip on the PVTA.

The implementation of this would consist of the following:
1. Downloading PVTA's GFTS data every so often (in accordance with #2)
2. Storing it
3. <b>Parsing it</b>
4. Presenting it
5. Tying it in with Avail's realtime data (trips and route IDs are not consistent across the 2 data sets)
   
   a. The best way I can think to accomplish this is by string comparison, ie:
   
   ```
    i. GTFS has Trip 1874459 at Stop 56 at 08:01:30 on a weekday.
    ii. Avail has sees a StopDeparture at Stop 56 for Route 20030, 
          Trip 30-5, on Date(01-21-16:T-080130)
   ```

In order for us to compare the two for real-time retrieval, we would have to:
1. Find 1874459 in GTFS's <code>Trips.csv</code>, see that it's 
       associated with the Route titled "30" with a headsign of 
      "North Amherst," and continue to step 2.
2. The StopIds are the same between Avail and GTFS, so we download 
        StopDeparture realtime data for the Stop in question.
3. Since GTFS's <b>RouteID</b>s are Avail's <b>ShortName</b>s, we 
        should be able to to look for upcoming Departures with that ShortName.
   
   It's not quite that easy, because Avail separates by RouteDirection 
       (ex: two 34s, one to Ohill and one to Mullins, and their respective departures, get two separate 
       entries in the root array).
   
      Because GTFS gives no semblance of Direction (N, S, UPW, DOW, etc), 
      we have to do, in Avail's data, the following:
4. In the root array returned, we must search every RouteDirection until we find
              one with a Trip inside of a Departure that matches the Route we're looking for.
   
   ```
          Each RouteDirection has a list of Deptartures.  Each Departure has a Trip.
          The Trip is the only part that contains a way for us to check 
          that we're looking at the correct Route.
   
         Use String comparison on the InternetServiceDesc of every Trip until we find one
         that matches the Headsign we got from GTFS.
   ```
5. Once we've done that, we need to check to see if the Departure time is the same.
   
   ```
          For the Departure that contains the Trip we determined to be correct above, 
         we should use moment.js to 'stringify' the departure time, since GTFS 
          and Avail have them in different formats.
   
        We use string comparison to see if they are the exact same.  If not, this is
        not the departure we're looking for.  Return to Step 4.
   ```
6. Assuming the RouteDirection and Trip check out, we can display this Departure to the user.

<b>NOTE</b>: These 6 steps really only apply to when the departure being searched for is in the next 3 hours (Avail's realtime window).  If there's no reason to use realtime data for it, we can just parse the GTFS CSV and display the scheduled departure.

**Comment by werebus** [comment]
Sounds more-or-less right, although PVTA has "plans" to switch to having Avail also provide the GTFS feed (rather than Hastus).  When that happens, it's likely that the trip ids will be easier to match up :pray:  Probably best to wait on this issue until they've resolved that one way or the other (check with @sherson)

Also, you'll want to consider loading the GTFS files into some sort of database.  Parsing them on the fly will be quite slow, I suspect, since you can't be sure of order in the files.

**Comment by akaplo** [comment]
[LocalForage](http://mozilla.github.io/localForage/) from Mozilla might be the way to go on supporting these.

**Comment by akaplo** [comment]
Seems as though Google has done some work for us too.
[Google GTFS Code Samples](https://developers.google.com/transit/gtfs-realtime/code-samples?hl=en)

**Comment by werebus** [comment]
So, those code samples are for GTFS _realtime_, which PVTA doesn't have implemented yet.  Avail does intend to offer GTFS realtime support at some point, but I don't know what the timeline is.

Arguably, GTFS in conjunction with GTFS realtime can communicate all the same information as Avail's API.

**Comment by sherson** [comment]
Once the dust settles from the MyAvail upgrade, I suspect we'll be close to GTFS-realtime. I'll be at PVTA next week and will ask.

**Comment by akaplo** [comment]
@werebus I gotcha.  Since I now seem to be pining for repositories that may be able to do a lot of GTFS parsing work for us, I stumbled upon [this](https://github.com/brendannee/node-gtfs) 5 minutes ago.
It seems legit.  

If we attempt to use this, we may have to do some editing because we aren't using Mongo, and Angular may make importing a little more complicated, but I'd say it's promising because he's definitely done most (if not all) of the heavy parsing for us.

@sherson good to know!  Would including GTFS realtime basically void all the work that relies on Avail realtime?  Not trying to sound bratty; an honest question.

**Comment by sherson** [comment]
Once it's in GTFS-realtime, I think we could choose to either use Avail's feed or GTFS'.

Also, the project manager was in a meeting when I went to ask about timeline, but I'll try again later today or tomorrow.

**Comment by akaplo** [comment]
@sherson did you ever hear from them?

**Comment by sherson** [comment]
Yes, sorry forgot to update this... I was told there is no timeline right now (they're dealing with bigger issues related to the MyAvail upgrade). I'm speculating, but it's probably months away.

For now we should continue working with the Avail feed (obviously) and we can reassess once GTFS-realtime launches.

**Comment by akaplo** [comment]
No big deal! Good to know. I still think we should include GTFS schedule data. Other than the time it would take to implement, I see no detriment to it. Does anyone else have thoughts on this?

In terms of implementation, I'm thinking about forking the schedule feed parser I linked to above and tweaking it to work with Angular and the SQLite databases that cordova supports.

**Comment by sherson** [comment]
> I still think we should include GTFS schedule data. 

Definitely. I initially mentioned GTFS since it's a good source for static (well, infrequently updated) schedule data, regardless of where we get the realtime data.

**Comment by akaplo** [comment]
Welp.
