### ISSUE TITLE
Mapping a Single Vehicle

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#98]
#94 partitioned the Map logic to consist of a service and two controllers: route-map and and stop-map.  route-map also plots all vehicles on a specific route, but what if you want to plot a single vehicle from its own detail page?  As of #94, you can't.

This is technically the expected behavior; as such, I'm not rolling back #94, as a PR addressing this issue would resolve it.

So, (@bgregg) we partitioned the logic correctly, but we forgot to add a vehicle-map-controller to account for this.  Doing so would resolve this issue.

**Comment by bgregg** [comment]
I'll get on it right away
